// هەموو وەرگێڕانەکانی پرۆژەکە لێرە کۆ دەکرێنەوە
const translations = {
    en: {
        welcome_text: "Welcome",
        nav:"Restaurant",
        nav1:"bakery",
        alphabakery:"ALPHA BAKERY",
        mojito:"mojito",
        path:"../../assets/test.jpeg",
        mojitoname1:"Classic Mojito",
        mojitoprice1:"3500 IQD",
        mojitoimg1:"",
         mojitoname2:"Strawberry Mojito",
        mojitoprice2:"4000 IQD",
        mojitoimg2:"",
         mojitoname3:"Blue Hawaii Mojito",
        mojitoprice3:"4000 IQD",
        mojitoimg3:"",
         mojitoname4:"Pomegranate Mojito",
        mojitoprice4:"4000 IQD",
        mojitoimg4:"",
         mojitoname5:"Peach Mojito",
        mojitoprice5:"4000 IQD",
        mojitoimg5:"",
         mojitoname6:"Passion Fruit Mojito",
        mojitoprice6:"4000 IQD",
        mojitoimg6:"",
         mojitoname7:"Blueberry Mojito",
        mojitoprice7:"4000 IQD",
        mojitoimg7:"",
         mojitoname8:"Mango Mojito",
        mojitoprice8:"4000 IQD",
        mojitoimg8:"",
         mojitoname9:"Pineapple Mojito",
        mojitoprice9:"4000 IQD",
        mojitoimg9:"",
         mojitoname10:"Alpha Mojito",
        mojitoprice10:"5000 IQD",
        mojitoimg10:"",
       /* //////////////////////////////////////////////////*/
       Juice:"Juice",
        Juicename1:"Orange",
        Juiceprice1:"4000 IQD",
        Juiceimg1:"",
         Juicename2:"Pomegranate",
        Juiceprice2:"4000 IQD",
        Juiceimg2:"",
         Juicename3:"Lemon Mint",
        Juiceprice3:"4000 IQD",
        Juiceimg3:"",
         Juicename4:"Pineapple",
        Juiceprice4:"4000 IQD",
        Juiceimg4:"",
         Juicename5:"Mango",
        Juiceprice5:"5000 IQD",
        Juiceimg5:"",
         Juicename6:"Banana Milk",
        Juiceprice6:"4000 IQD",
        Juiceimg6:"",
         Juicename7:"Avocado",
        Juiceprice7:"5000 IQD",
        Juiceimg7:"",
         Juicename8:"Cocktail",
        Juiceprice8:"4000 IQD",
        Juiceimg8:"",
         Juicename9:"Alpha",
        Juiceprice9:"5500 IQD",
        Juiceimg9:"",
           /* //////////////////////////////////////////////////*/
           IceTea:"Ice Tea",
        IceTeaname1:"Peach Ice Tea",
        IceTeaprice1:"5000 IQD",
        IceTeaimg1:"",
         IceTeaname2:"Lemon Ice Tea",
        IceTeaprice2:"5000 IQD",
        IceTeaimg2:"",
         IceTeaname3:"Mango Ice Tea",
        IceTeaprice3:"5000 IQD",
        IceTeaimg3:"",
         IceTeaname4:"Passion Fruit Ice Tea",
        IceTeaprice4:"5000 IQD",
        IceTeaimg4:"",
         /* //////////////////////////////////////////////////*/
        Mocktail:"Mocktail",
        Mocktailname1:"Alpha Mocktail",
        Mocktailprice1:"6000 IQD",
        Mocktailimg1:"",
         Mocktailname2:"Lavender Mocktail",
        Mocktailprice2:"5000 IQD",
        Mocktailimg2:"",
         Mocktailname3:"Pina Colada Mocktail",
        Mocktailprice3:"5000 IQD",
        Mocktailimg3:"",
         Mocktailname4:"Berry Blast Mocktail",
        Mocktailprice4:"5000 IQD",
        Mocktailimg4:"Ice Tea",
           Mocktailname5:"Ocean Dream Mocktail",
        Mocktailprice5:"5000 IQD",
        Mocktailimg5:"",
 /* //////////////////////////////////////////////////*/
          Milkshake:"Milkshake",
        Milkshakename1:"Nutella Milkshake",
        Milkshakeprice1:"5000 IQD",
        Milkshakeimg1:"",
         Milkshakename2:"Lotus Milkshake",
        Milkshakeprice2:"5000 IQD",
        Milkshakeimg2:"",
         Milkshakename3:"Pistachio Milkshake",
        Milkshakeprice3:"5000 IQD",
        Milkshakeimg3:"",
         Milkshakename4:"Vanilla Milkshake",
        Milkshakeprice4:"5000 IQD",
        Milkshakeimg4:"",
         Milkshakename5:"Oreo Milkshake",
        Milkshakeprice5:"5000 IQD",
        Milkshakeimg5:"",
         Milkshakename6:"Kinder Milkshake",
        Milkshakeprice6:"5000 IQD",
        Milkshakeimg6:"",
         Milkshakename7:"Strawberry Milkshake",
        Milkshakeprice7:"5000 IQD",
        Milkshakeimg7:"",
         Milkshakename8:"Chocolate Milkshake",
        Milkshakeprice8:"5000 IQD",
        Milkshakeimg8:"",
        Milkshakename9:"Caramel Milkshake",
        Milkshakeprice9:"5000 IQD",
        Milkshakeimg9:"",
        Milkshakename10:"Alpha Milkshake",
        Milkshakeprice10:"6000 IQD",
        Milkshakeimg10:"",
 /* //////////////////////////////////////////////////*/
         Frappe:"Frappe",
        Frappename1:"Chocolate Frappe",
        Frappeprice1:"5000 IQD",
        Frappeimg1:"",
         Frappename2:"Caramel Frappe",
        Frappeprice2:"5000 IQD",
        Frappeimg2:"",
         Frappename3:"Cookies Frappe",
        Frappeprice3:"5000 IQD",
        Frappeimg3:"",
         Frappename4:"Strawberry Frappe",
        Frappeprice4:"5000 IQD",
        Frappeimg4:"Ice Tea",
           Frappename5:"Strawberry Frappe",
        Frappeprice5:"5000 IQD",
        Frappeimg5:"",
         /* //////////////////////////////////////////////////*/
         Smoothie:"Smoothie",
        Smoothiename1:"Mango Smoothie",
        Smoothieprice1:"4500 IQD",
        Smoothieimg1:"",
         Smoothiename2:"Strawberry Smoothie",
        Smoothieprice2:"4500 IQD",
        Smoothieimg2:"",
         Smoothiename3:"Blueberry Smoothie",
        Smoothieprice3:"4500 IQD",
        Smoothieimg3:"",
         Smoothiename4:"Pina Colada Smoothie",
        Smoothieprice4:"4500 IQD",
        Smoothieimg4:"Ice Tea",
           Smoothiename5:"Peach Smoothie",
       Smoothieprice5:"4500 IQD",
        Smoothieimg5:"",
            Smoothiename6:"Alpha Smoothie",
        Smoothieprice6:"5500 IQD",
        Smoothieimg6:"",
        /* //////////////////////////////////////////////////*/
          IcedLatte:"Iced Latte",
        IcedLattename1:"Iced Latte",
        IcedLatteprice1:"4500 IQD",
        IcedLatteimg1:"",
         IcedLattename2:"Iced Vanilla Latte",
        IcedLatteprice2:"5000 IQD",
        IcedLatteimg2:"",
         IcedLattename3:"Iced Caramel Latte",
        IcedLatteprice3:"5000 IQD",
        IcedLatteimg3:"",
         IcedLattename4:"Iced Pistachio Latte",
        IcedLatteprice4:"5000 IQD",
        IcedLatteimg4:"",
         IcedLattename5:"Iced Lotus Latte",
        IcedLatteprice5:"5000 IQD",
        IcedLatteimg5:"",
         IcedLattename6:"Iced Mocha",
        IcedLatteprice6:"5000 IQD",
        IcedLatteimg6:"",
         IcedLattename7:"Iced White Mocha",
        IcedLatteprice7:"5000 IQD",
        IcedLatteimg7:"",
         IcedLattename8:"Iced Rose Latte",
        IcedLatteprice8:"5000 IQD",
        IcedLatteimg8:"",
        IcedLattename9:"Iced Spanish Latte",
        IcedLatteprice9:"5000 IQD",
        IcedLatteimg9:"",
        IcedLattename10:"Iced Coconut Latte",
        IcedLatteprice10:"5000 IQD",
        IcedLatteimg10:"",
         IcedLattename11:"Iced Strawberry Latte",
        IcedLatteprice11:"5000 IQD",
        IcedLatteimg11:"",
         IcedLattename12:"Iced Lavender Latte",
        IcedLatteprice12:"5000 IQD",
        IcedLatteimg12:"",
          /* //////////////////////////////////////////////////*/
          HotLatte:"Hot Latte",
        HotLattename1:"Caffe Latte",
        HotLatteprice1:"4000 IQD",
        HotLatteimg1:"",
         HotLattename2:"Vanilla Latte",
        HotLatteprice2:"4500 IQD",
        HotLatteimg2:"",
         HotLattename3:"Caramel Latte",
        HotLatteprice3:"4500 IQD",
        HotLatteimg3:"",
         HotLattename4:"Spanish Latte",
        HotLatteprice4:"4500 IQD",
        HotLatteimg4:"",
         HotLattename5:"Lotus Latte",
        HotLatteprice5:"4500 IQD",
        HotLatteimg5:"",
         HotLattename6:"Pistachio Latte",
        HotLatteprice6:"4500 IQD",
        HotLatteimg6:"",
         HotLattename7:"Rose Latte",
        HotLatteprice7:"4500 IQD",
        HotLatteimg7:"",
         HotLattename8:"Mocha Latte",
        HotLatteprice8:"4500 IQD",
        HotLatteimg8:"",
        HotLattename9:"White Mocha Latte",
        HotLatteprice9:"4500 IQD",
        HotLatteimg9:"",
        HotLattename10:"Coconut Latte",
        HotLatteprice10:"4500 IQD",
        HotLatteimg10:"",
         HotLattename11:"Lavender Latte",
        HotLatteprice11:"4500 IQD",
        HotLatteimg11:"",
/* //////////////////////////////////////////////////*/
         HotDrinks:"Hot Drinks",
        HotDrinksname1:"Espresso Single",
        HotDrinksprice1:"2500 IQD",
        HotDrinksimg1:"",
         HotDrinksname2:"Espresso Double",
        HotDrinksprice2:"3500 IQD",
        HotDrinksimg2:"",
         HotDrinksname3:"Ristretto",
        HotDrinksprice3:"2500 IQD",
        HotDrinksimg3:"",
         HotDrinksname4:"Macchiato",
        HotDrinksprice4:"3000 IQD",
        HotDrinksimg4:"",
         HotDrinksname5:"Lungo",
        HotDrinksprice5:"3000 IQD",
        HotDrinksimg5:"",
         HotDrinksname6:"Con Panna",
        HotDrinksprice6:"3500 IQD",
        HotDrinksimg6:"",
         HotDrinksname7:"Americano",
        HotDrinksprice7:"4000 IQD",
        HotDrinksimg7:"",
         HotDrinksname8:"Cortado",
        HotDrinksprice8:"4000 IQD",
        HotDrinksimg8:"",
        HotDrinksname9:"Affogato",
        HotDrinksprice9:"3500 IQD",
        HotDrinksimg9:"",
        HotDrinksname10:"Flat White",
        HotDrinksprice10:"4000 IQD",
        HotDrinksimg10:"",
         HotDrinksname11:"Piccolo Latte",
        HotDrinksprice11:"4000 IQD",
        HotDrinksimg11:"",
         HotDrinksname12:"Chemex",
        HotDrinksprice12:"5000 IQD",
        HotDrinksimg12:"",
         HotDrinksname13:"V60",
        HotDrinksprice13:"5000 IQD",
        HotDrinksimg13:"",
         HotDrinksname14:"Turkish Coffee",
        HotDrinksprice14:"2000 IQD",
        HotDrinksimg14:"",
         HotDrinksname15:"Turkish Coffee Doubl",
        HotDrinksprice15:"3000 IQD",
        HotDrinksimg15:"",
         HotDrinksname16:"Arabic Coffee",
        HotDrinksprice16:"2000 IQD",
        HotDrinksimg16:"",
         HotDrinksname17:"Arabic Coffee Double",
        HotDrinksprice17:"3000 IQD",
        HotDrinksimg17:"",
         HotDrinksname18:"Mistak Coffee",
        HotDrinksprice18:"2000 IQD",
        HotDrinksimg18:"",
         HotDrinksname19:"Mistak Coffee Double",
        HotDrinksprice19:"3000 IQD",
        HotDrinksimg19:"",
         HotDrinksname20:"Kazan Coffee",
        HotDrinksprice20:"2000 IQD",
        HotDrinksimg20:"",
        HotDrinksname21:"Kazan Coffee Double",
        HotDrinksprice21:"3000 IQD",
        HotDrinksimg21:"",
        HotDrinksname22:"Hot Chocolate",
        HotDrinksprice22:"4000 IQD",
        HotDrinksimg22:"",
         HotDrinksname23:"Sahlab",
        HotDrinksprice23:"4000 IQD",
        HotDrinksimg23:"",
         HotDrinksname24:"Plain Milk",
        HotDrinksprice24:"2500 IQD",
        HotDrinksimg24:"",
           HotDrinksname25:"Honey Milk",
        HotDrinksprice25:"3500 IQD",
        HotDrinksimg25:"",
           HotDrinksname26:"Nescafe",
        HotDrinksprice26:"4000 IQD",
        HotDrinksimg26:"",
           HotDrinksname27:"Cappuccino",
        HotDrinksprice27:"4000 IQD",
        HotDrinksimg27:"",
         /* //////////////////////////////////////////////////*/
         EnergyMix:"Energy Mix",
        EnergyMixname1:"Red Bull Mix Alpha",
        EnergyMixprice1:"5500 IQD",
        EnergyMiximg1:"",
         EnergyMixname2:"Red Bull Mix",
       EnergyMixprice2:"4500 IQD",
        EnergyMiximg2:"",
         EnergyMixname3:"Smart Mix Alpha",
        EnergyMixprice3:"3500 IQD",
        EnergyMiximg3:"",
         EnergyMixname4:"Smart Mix",
        EnergyMixprice4:"2500 IQD",
        EnergyMiximg4:"Ice Tea",
           EnergyMixname5:"White Tiger Mix Alpha",
       EnergyMixprice5:"4000 IQD",
        EnergyMiximg5:"",
            EnergyMixname6:"White Tiger Mix",
        EnergyMixprice6:"3500 IQD",
       EnergyMiximg6:"",
        /* //////////////////////////////////////////////////*/
         Desserts:"Desserts",
        Dessertsname1: "Blueberry Cheesecake", Dessertsprice1: "4000 IQD", Dessertsimg1: "",
        Dessertsname2: "Lotus Cheesecake", Dessertsprice2: "4000 IQD", Dessertsimg2: "",
        Dessertsname3: "Pistachio Cheesecake", Dessertsprice3: "4000 IQD", Dessertsimg3: "",
        Dessertsname4: "Oreo Cheesecake", Dessertsprice4: "4000 IQD", Dessertsimg4: "",
        Dessertsname5: "Caramel Trilece", Dessertsprice5: "2000 IQD", Dessertsimg5: "",
        Dessertsname6: "Tiramisu", Dessertsprice6: "3000 IQD", Dessertsimg6: "",
        Dessertsname7: "Red Velvet Slice Cake", Dessertsprice7: "3000 IQD", Dessertsimg7: "",
        Dessertsname8: "Pistachio Slice Cake", Dessertsprice8: "3000 IQD", Dessertsimg8: "",
        Dessertsname9: "Blueberry Slice Cake", Dessertsprice9: "3000 IQD", Dessertsimg9: "",
        Dessertsname10: "Black Forest Slice Cake", Dessertsprice10: "4000 IQD", Dessertsimg10: "",
        Dessertsname11: "Matilda Slice Cake", Dessertsprice11: "4000 IQD", Dessertsimg11: "",
         Dessertsname12:"Crepe",
        Dessertsprice12:"4000 IQD",
        Dessertsimg12:"",
         Dessertsname13:"Mini Pancakes",
       Dessertsprice13:"4000 IQD",
        Dessertsimg13:"",
/* //////////////////////////////////////////////////*/
         Pastries:"Pastries",
        Pastriesname1:"Potato Pastry",
        Pastriesprice1:"750 IQD",
        Pastriesimg1:"",
         Pastriesname2:"Cheese & Cream Pastry",
        Pastriesprice2:"750 IQD",
        Pastriesimg2:"",
         Pastriesname3:"Lork",
        Pastriesprice3:"750 IQD",
        Pastriesimg3:"",
         Pastriesname4:"Nutella Pastry",
        Pastriesprice4:"750 IQD",
        Pastriesimg4:"",
         Pastriesname5:"Sausage",
        Pastriesprice5:"500 IQD",
        Pastriesimg5:"",
         Pastriesname6:"Simit",
        Pastriesprice6:"500 IQD",
        Pastriesimg6:"",
         Pastriesname7:"Stuffed Mini Simit",
        Pastriesprice7:"500 IQD",
        Pastriesimg7:"",
         Pastriesname8:"Mini Coriander Pastry",
        Pastriesprice8:"500 IQD",
        Pastriesimg8:"",
        Pastriesname9:"Mini Pizza",
        Pastriesprice9:"1500 IQD",
        Pastriesimg9:"",
        Pastriesname10:"Mini Cheese Pastry",
        Pastriesprice10:"1500 IQD",
        Pastriesimg10:"",
         Pastriesname11:"Mini Lork Cheese Pastry",
        Pastriesprice11:"1500 IQD",
        Pastriesimg11:"",
/* //////////////////////////////////////////////////*/
          Pastriesperkilo:"Pastries kilo",
        Pastriesperkiloname1:"Barazek",
        Pastriesperkiloprice1:"8000 IQD",
        Pastriesperkiloimg1:"",
         Pastriesperkiloname2:"Barazek diet",
        Pastriesperkiloprice2:"10000 IQD",
        Pastriesperkiloimg2:"",
         Pastriesperkiloname3:"shkrmlk Turki",
        Pastriesperkiloprice3:"8000 IQD",
        Pastriesperkiloimg3:"",
         Pastriesperkiloname4:"Coconut Macarons",
        Pastriesperkiloprice4:"12000 IQD",
        Pastriesperkiloimg4:"",
           Pastriesperkiloname5:"Chabura",
        Pastriesperkiloprice5:"12000 IQD",
        Pastriesperkiloimg5:"",
        /* /////////////////// Croissant English /////////////////// */
        Croissant: "Croissant",
        Croissantname1: "Plain Croissant", Croissantprice1: "1500 IQD", Croissantimg1: "",
        Croissantname2: "Palmier Croissant", Croissantprice2: "2000 IQD", Croissantimg2: "",
        Croissantname3: "Thyme Croissant", Croissantprice3: "2000 IQD", Croissantimg3: "",
        Croissantname4: "Chocolate Croissant", Croissantprice4: "2000 IQD", Croissantimg4: "",
        Croissantname5: "Nutella Croissant", Croissantprice5: "3000 IQD", Croissantimg5: "",
        Croissantname6: "Fruit Stuffed Croissant", Croissantprice6: "3000 IQD", Croissantimg6: "",
        Croissantname7: "Pistachio Croissant", Croissantprice7: "4000 IQD", Croissantimg7: "",
        Croissantname8: "Dubai Chocolate Croissant", Croissantprice8: "5000 IQD", Croissantimg8: "",
        Croissantname9: "Blueberry Tart Croissant", Croissantprice9: "4000 IQD", Croissantimg9: "",
        Croissantname10: "Strawberry Tart Croissant", Croissantprice10: "4000 IQD", Croissantimg10: "",
        Croissantname11: "New York Roll Croissant", Croissantprice11: "4000 IQD", Croissantimg11: "",
        Croissantname12: "Square Stuffed Croissant", Croissantprice12: "4000 IQD", Croissantimg12: "",
        /* /////////////////// Donuts English /////////////////// */
        Donuts: "Donuts",
        Donutsname1: "Decorated Donut", Donutsprice1: "1500 IQD", Donutsimg1: "",
        Donutsname2: "Nutella Stuffed Donut", Donutsprice2: "3000 IQD", Donutsimg2: "",
        Donutsname3: "Blueberry Stuffed Donut", Donutsprice3: "3000 IQD", Donutsimg3: "",
        Donutsname4: "Strawberry Stuffed Donut", Donutsprice4: "3000 IQD", Donutsimg4: "",
        Donutsname5: "Pastry Cream Stuffed Donut", Donutsprice5: "2000 IQD", Donutsimg5: "",
        Donutsname6: "Dubai Chocolate Stuffed Donut", Donutsprice6: "3000 IQD", Donutsimg6: "",
        Donutsname7: "Mini Sugar Donut", Donutsprice7: "250 IQD", Donutsimg7: "",
        Donutsname8: "Mini Decorated Donut", Donutsprice8: "750 IQD", Donutsimg8: "",
        Donutsname9: "Mini Stuffed Donut", Donutsprice9: "1000 IQD", Donutsimg9: "",
        /* /////////////////// Eclair English /////////////////// */
        Eclair: "Eclair",
        Eclairname1: "Pistachio Eclair", Eclairprice1: "2000 IQD", Eclairimg1: "",
        Eclairname2: "Lotus Eclair", Eclairprice2: "2000 IQD", Eclairimg2: "",
        Eclairname3: "Oreo Eclair", Eclairprice3: "2000 IQD", Eclairimg3: "",
        Eclairname4: "Blueberry Eclair", Eclairprice4: "2000 IQD", Eclairimg4: "",
        /* /////////////////// Cookies English /////////////////// */
        Cookies: "Cookies",
        Cookiesname1: "Nutella Cookies", Cookiesprice1: "2500 IQD", Cookiesimg1: "",
        Cookiesname2: "Kinder Cookies", Cookiesprice2: "2500 IQD", Cookiesimg2: "",
        Cookiesname3: "Mango Cookies", Cookiesprice3: "2500 IQD", Cookiesimg3: "",
        Cookiesname4: "Red Velvet Cookies", Cookiesprice4: "2500 IQD", Cookiesimg4: "",
        Cookiesname5: "Plain Cookies", Cookiesprice5: "2000 IQD", Cookiesimg5: "",
        Cookiesname6: "Pistachio Cookies", Cookiesprice6: "2500 IQD", Cookiesimg6: "",

 /* ///////////////////  zmnan /////////////////// */
  /* ///////////////////  zman /////////////////// */
w1:"Western food",
w2:"Eastern food",
alpharest:"ALPHA RESTAURANT",
/* /////////////////// Pizza English /////////////////// */
        Pizza: "Pizza",
        Pizzaname1: "Mixed Pizza", Pizzaprice1: "11,000 IQD", Pizzaimg1: "",
        Pizzaname2: "Vegetable Pizza", Pizzaprice2: "8,000 IQD", Pizzaimg2: "",
        Pizzaname3: "Value Pizza", Pizzaprice3: "9,000 IQD", Pizzaimg3: "",
        Pizzaname4: "Meat Pizza", Pizzaprice4: "11,000 IQD", Pizzaimg4: "",
        Pizzaname5: "Chicken Pizza", Pizzaprice5: "9,000 IQD", Pizzaimg5: "",
        Pizzaname6: "Pepperoni Pizza", Pizzaprice6: "9,000 IQD", Pizzaimg6: "",
        Pizzaname7: "Chips Pizza", Pizzaprice7: "11,000 IQD", Pizzaimg7: "",
        Pizzaname8: "Tuna Pizza", Pizzaprice8: "9,000 IQD", Pizzaimg8: "",
        Pizzaname9: "Chicken Chips Pizza", Pizzaprice9: "9,000 IQD", Pizzaimg9: "",
        Pizzaname10: "Mexican Pizza", Pizzaprice10: "11,000 IQD", Pizzaimg10: "",
        Pizzaname11: "Pizza Calzone", Pizzaprice11: "10,000 IQD", Pizzaimg11: "",
        Pizzaname12: "Pizza Margherita", Pizzaprice12: "7,000 IQD", Pizzaimg12: "",
        Pizzaname13: "Kid Pizza", Pizzaprice13: "7,000 IQD", Pizzaimg13: "",
        Pizzaname14: "Pizza Chawchaw", Pizzaprice14: "9,000 IQD", Pizzaimg14: "",
/* /////////////////// Burger English /////////////////// */
        Burger: "Burger",
        Burgername1: "Meat Burger", Burgerprice1: "5,000 IQD", Burgerimg1: "",
        Burgername2: "Chicken Burger", Burgerprice2: "4,000 IQD", Burgerimg2: "",
        Burgername3: "Chicken Cheeseburger", Burgerprice3: "7,000 IQD", Burgerimg3: "",
        Burgername4: "Cheese Burger", Burgerprice4: "8,000 IQD", Burgerimg4: "",
        Burgername5: "Double Meat Burger", Burgerprice5: "12,000 IQD", Burgerimg5: "",
        Burgername6: "Double Chicken Burger", Burgerprice6: "11,000 IQD", Burgerimg6: "",
        Burgername7: "Alpha Burger (Meat)", Burgerprice7: "12,000 IQD", Burgerimg7: "",
        Burgername8: "Alpha Chicken Burger", Burgerprice8: "10,000 IQD", Burgerimg8: "",
        /* /////////////////// Sandwich English /////////////////// */
        Sandwich: "Sandwich",
        Sandwichname1: "Chicken Sandwich", Sandwichprice1: "7,000 IQD", Sandwichimg1: "",
        Sandwichname2: "Meat Sandwich", Sandwichprice2: "10,000 IQD", Sandwichimg2: "",
        Sandwichname3: "Chips Sandwich", Sandwichprice3: "9,000 IQD", Sandwichimg3: "",
        /* /////////////////// Chicken & Saj English /////////////////// */
        ChickenSaj: "Chicken & Saj",
        ChickenSajname1: "Chicken Roll", ChickenSajprice1: "4,000 IQD", ChickenSajimg1: "",
        ChickenSajname2: "Chicken Pita", ChickenSajprice2: "3,000 IQD", ChickenSajimg2: "",
        ChickenSajname3: "Chicken Saj", ChickenSajprice3: "7,000 IQD", ChickenSajimg3: "",
        ChickenSajname4: "Alpha Chicken Saj", ChickenSajprice4: "10,000 IQD", ChickenSajimg4: "",
        ChickenSajname5: "Chicken Chips Saj", ChickenSajprice5: "8,000 IQD", ChickenSajimg5: "",
        ChickenSajname6: "Chicken Escalope", ChickenSajprice6: "8,000 IQD", ChickenSajimg6: "",
        ChickenSajname7: "Kid Kentucky", ChickenSajprice7: "6,000 IQD", ChickenSajimg7: "",
        /* /////////////////// Meat & Saj English /////////////////// */
        MeatSaj: "Meat & Saj",
        MeatSajname1: "Meat Roll", MeatSajprice1: "6,000 IQD", MeatSajimg1: "",
        MeatSajname2: "Alpha Roll", MeatSajprice2: "8,000 IQD", MeatSajimg2: "",
        MeatSajname3: "Meat Pita", MeatSajprice3: "4,000 IQD", MeatSajimg3: "",
        MeatSajname4: "Alpha Pita", MeatSajprice4: "5,000 IQD", MeatSajimg4: "",
        MeatSajname5: "Meat Saj", MeatSajprice5: "9,000 IQD", MeatSajimg5: "",
        MeatSajname6: "Meat Chips Saj", MeatSajprice6: "10,000 IQD", MeatSajimg6: "",
        MeatSajname7: "Alpha Meat Saj", MeatSajprice7: "11,000 IQD", MeatSajimg7: "",
        /* /////////////////// Fries English /////////////////// */
        Fries: "Fries",
        Appetizersname1: "French Fries", Appetizersprice1: "3,000 IQD", Appetizersimg1: "",
        Appetizersname2: "Cheetos Fries", Appetizersprice2: "6,000 IQD", Appetizersimg2: "",
        Appetizersname3: "Cheese Fries", Appetizersprice3: "5,000 IQD", Appetizersimg3: "",
        Appetizersname4: "Wedges", Appetizersprice4: "5,000 IQD", Appetizersimg4: "",
        Appetizersname5: "Corn", Appetizersprice5: "5,000 IQD", Appetizersimg5: "",
        Appetizersname6: "Onion Rings", Appetizersprice6: "5,000 IQD", Appetizersimg6: "",
        Appetizersname7: "Baked Potato", Appetizersprice7: "6,000 IQD", Appetizersimg7: "",
        /* /////////////////// Alpha Special English /////////////////// */
        AlphaSpecial: "Alpha Special",
        AlphaSpecialname1: "Alpha Chicken", AlphaSpecialprice1: "9,000 IQD", AlphaSpecialimg1: "",
        AlphaSpecialname2: "Alpha Kebab", AlphaSpecialprice2: "12,000 IQD", AlphaSpecialimg2: "",
        AlphaSpecialname3: "Beliza Chicken", AlphaSpecialprice3: "13,000 IQD", AlphaSpecialimg3: "",
        AlphaSpecialname4: "Beef Sandwich", AlphaSpecialprice4: "12,000 IQD", AlphaSpecialimg4: "",
        AlphaSpecialname5: "Alpha Greek", AlphaSpecialprice5: "12,000 IQD", AlphaSpecialimg5: "",
        AlphaSpecialname6: "Alpha Chicken Beliza", AlphaSpecialprice6: "13,000 IQD", AlphaSpecialimg6: "",
        AlphaSpecialname7: "Alpha Polo Chicken", AlphaSpecialprice7: "11,000 IQD", AlphaSpecialimg7: "",
        AlphaSpecialname8: "Alpha Polo", AlphaSpecialprice8: "13,000 IQD", AlphaSpecialimg8: "",
        AlphaSpecialname9: "Beliza Corn", AlphaSpecialprice9: "13,000 IQD", AlphaSpecialimg9: "",
        AlphaSpecialname10: "Beliza Corn Chicken", AlphaSpecialprice10: "12,000 IQD", AlphaSpecialimg10: "",
        AlphaSpecialname11: "Meat Mushroom", AlphaSpecialprice11: "13,000 IQD", AlphaSpecialimg11: "",
        AlphaSpecialname12: "Alpha Beliza", AlphaSpecialprice12: "14,000 IQD", AlphaSpecialimg12: "",
        /* /////////////////// Box Meals English /////////////////// */
        BoxMeals: "Box Meals",
        BoxMealsname1: "Chicken Box", BoxMealsprice1: "8,000 IQD", BoxMealsimg1: "",
        BoxMealsname2: "Meat Box", BoxMealsprice2: "10,000 IQD", BoxMealsimg2: "",
        BoxMealsname3: "Alpha Meat Box", BoxMealsprice3: "11,000 IQD", BoxMealsimg3: "",
        BoxMealsname4: "Alpha Chicken Box", BoxMealsprice4: "10,000 IQD", BoxMealsimg4: "",
        BoxMealsname5: "Shawarma Box", BoxMealsprice5: "4,000 IQD", BoxMealsimg5: "",
        BoxMealsname6: "Chicken Shawarma Box", BoxMealsprice6: "6,000 IQD", BoxMealsimg6: "",
        /* /////////////////// Pasta English /////////////////// */
        Pasta: "Pasta",
        Pastaname1: "Chicken Pasta", Pastaprice1: "9,000 IQD", Pastaimg1: "",
        Pastaname2: "Beef Pasta", Pastaprice2: "10,000 IQD", Pastaimg2: "",
        Pastaname3: "Fettuccine Alfredo", Pastaprice3: "10,000 IQD", Pastaimg3: "",
        Pastaname4: "Chicken Fettuccine", Pastaprice4: "9,000 IQD", Pastaimg4: "",
        Pastaname5: "Fettuccine", Pastaprice5: "10,000 IQD", Pastaimg5: "",
        /* /////////////////// Diet Meals English /////////////////// */
        DietMeals: "Diet Meals",
        DietMealsname1: "Chicken Diet", DietMealsprice1: "7,000 IQD", DietMealsimg1: "",
        DietMealsname2: "Meat Diet", DietMealsprice2: "11,000 IQD", DietMealsimg2: "",
        DietMealsname3: "Salmon Diet", DietMealsprice3: "14,000 IQD", DietMealsimg3: "",
        /* /////////////////// Steak English /////////////////// */
        Steak: "Steak",
        Steakname1: "Meat Steak", Steakprice1: "14,000 IQD", Steakimg1: "",
        Steakname2: "Chicken Steak", Steakprice2: "12,000 IQD", Steakimg2: "",
        Steakname3: "Alpha Stebeliza", Steakprice3: "12,000 IQD", Steakimg3: "",
        Steakname4: "Salmon Steak", Steakprice4: "16,000 IQD", Steakimg4: "",
        /* /////////////////// Shrimp English /////////////////// */
        Shrimp: "Shrimp",
        Shrimpname1: "Shrimp", Shrimpprice1: "15,000 IQD", Shrimpimg1: "",
        Shrimpname2: "Shrimp Chili", Shrimpprice2: "12,000 IQD", Shrimpimg2: "",
        /* /////////////////// Salads English /////////////////// */
        Salads: "Salads",
        Saladsname1: "Caesar Salad", Saladsprice1: "6,000 IQD", Saladsimg1: "",
        Saladsname2: "Fruca Salad", Saladsprice2: "5,000 IQD", Saladsimg2: "",
        Saladsname3: "Broccoli Salad", Saladsprice3: "7,000 IQD", Saladsimg3: "",
        Saladsname4: "Greek Salad", Saladsprice4: "5,000 IQD", Saladsimg4: "",
        Saladsname5: "Roka Salad", Saladsprice5: "5,000 IQD", Saladsimg5: "",
     /* /////////////////// Steak English /////////////////// */
        cola: "Drinks",
        colaname1: "Coca-Cola", colaprice1: "500 IQD", colaimg1: "",
        colaname2: "Sprite", colaprice2: "500 IQD", colaimg2: "",
        colaname3: "Fanta", colaprice3: "500 IQD", colaimg3: "",
        colakname4: "Water", colaprice4: "250 IQD", colaimg4: "",

        dir: "ltr",
        
    },


























    ku: {
        welcome_text: "بخێرهاتن",
        nav:"خوارنگەهـ",
        nav1:"bakery",
        alphabakery:"ئەلفا بێکری",
        mojito:"موهيتو",
        path:"../../assets/test.jpeg",
         mojitoname1:"کلاسیک موهیتو",
        mojitoprice1:"3500 IQD",
        mojitoimg1:"",
         mojitoname2:"موهیتویا فەرەولایێ",
        mojitoprice2:"4000 IQD",
        mojitoimg2:"",
         mojitoname3:"بلو هەوای موهیتو",
        mojitoprice3:"4000 IQD",
        mojitoimg3:"",
         mojitoname4:"موهیتویا هنارێ",
        mojitoprice4:"4000 IQD",
        mojitoimg4:"",
         mojitoname5:"موهیتویا خۆخێ",
        mojitoprice5:"4000 IQD",
        mojitoimg5:"",
         mojitoname6:"پاشن فروت موهیتو",
        mojitoprice6:"4000 IQD",
        mojitoimg6:"",
         mojitoname7:"بلوبێری موهیتو",
        mojitoprice7:"4000 IQD",
        mojitoimg7:"",
         mojitoname8:"مانگو موهیتو",
        mojitoprice8:"4000 IQD",
        mojitoimg8:"",
         mojitoname9:"موهیتویا ئەنەناسێ",
        mojitoprice9:"4000 IQD",
        mojitoimg9:"",
         mojitoname10:"ئەلفا موهیتو",
        mojitoprice10:"5000 IQD",
        mojitoimg10:"",
       /* //////////////////////////////////////////////////*/
       Juice:"شەربەت",
        Juicename1:"پرتەقال",
        Juiceprice1:"4000 IQD",
        Juiceimg1:"",
         Juicename2:"هنار",
        Juiceprice2:"4000 IQD",
        Juiceimg2:"",
         Juicename3:"لەیمون و نەعنا",
        Juiceprice3:"4000 IQD",
        Juiceimg3:"",
         Juicename4:"ئەنەناس",
        Juiceprice4:"4000 IQD",
        Juiceimg4:"",
         Juicename5:"مانگو",
        Juiceprice5:"5000 IQD",
        Juiceimg5:"",
         Juicename6:"شیرموز",
        Juiceprice6:"4000 IQD",
        Juiceimg6:"",
         Juicename7:"ئەڤوکادو",
        Juiceprice7:"5000 IQD",
        Juiceimg7:"",
         Juicename8:"کوکتێل",
        Juiceprice8:"4000 IQD",
        Juiceimg8:"",
         Juicename9:"ئەلفا",
        Juiceprice9:"5500 IQD",
        Juiceimg9:"",
           /* //////////////////////////////////////////////////*/
           IceTea:"ئایس تی",
        IceTeaname1:"خۆخ ئایس تی",
        IceTeaprice1:"5000 IQD",
        IceTeaimg1:"",
         IceTeaname2:"لەیمون ئایس تی",
        IceTeaprice2:"5000 IQD",
        IceTeaimg2:"",
         IceTeaname3:"مانگو ئایس تی",
        IceTeaprice3:"5000 IQD",
        IceTeaimg3:"",
         IceTeaname4:"پاشن فروت ئایس تی",
        IceTeaprice4:"5000 IQD",
        IceTeaimg4:"",
         /* //////////////////////////////////////////////////*/
        Mocktail:"کوکتێل",
        Mocktailname1:"کوکتێلا ئەلفا",
        Mocktailprice1:"6000 IQD",
        Mocktailimg1:"",
         Mocktailname2:"لاڤندر کوکتێل",
        Mocktailprice2:"5000 IQD",
        Mocktailimg2:"",
         Mocktailname3:"پینا کولادا کوکتێل",
        Mocktailprice3:"5000 IQD",
        Mocktailimg3:"",
         Mocktailname4:"بێری بلاست کوکتێل",
        Mocktailprice4:"5000 IQD",
        Mocktailimg4:"ئایس تی",
           Mocktailname5:"ئوشن دریم کوکتێل",
        Mocktailprice5:"5000 IQD",
        Mocktailimg5:"",
 /* //////////////////////////////////////////////////*/
          Milkshake:"مێلکشەیک",
        Milkshakename1:"نوتێلا مێلکشەیک",
        Milkshakeprice1:"5000 IQD",
        Milkshakeimg1:"",
         Milkshakename2:"لوتوس مێلکشەیک",
        Milkshakeprice2:"5000 IQD",
        Milkshakeimg2:"",
         Milkshakename3:"فستەق مێلکشەیک",
        Milkshakeprice3:"5000 IQD",
        Milkshakeimg3:"",
         Milkshakename4:"ڤانێلا مێلکشەیک",
        Milkshakeprice4:"5000 IQD",
        Milkshakeimg4:"",
         Milkshakename5:"ئوریو مێلکشەیک",
        Milkshakeprice5:"5000 IQD",
        Milkshakeimg5:"",
         Milkshakename6:"کیندەر مێلکشەیک",
        Milkshakeprice6:"5000 IQD",
        Milkshakeimg6:"",
         Milkshakename7:"فەرەولا مێلکشەیک",
        Milkshakeprice7:"5000 IQD",
        Milkshakeimg7:"",
         Milkshakename8:"چوکولات مێلکشەیک",
        Milkshakeprice8:"5000 IQD",
        Milkshakeimg8:"",
        Milkshakename9:"کارامێل مێلکشەیک",
        Milkshakeprice9:"5000 IQD",
        Milkshakeimg9:"",
        Milkshakename10:"ئەلفا مێلکشەیک",
        Milkshakeprice10:"6000 IQD",
        Milkshakeimg10:"",

/* //////////////////////////////////////////////////*/
         Frappe:"فراپێ",
        Frappename1:"چوکلێت فراپێ",
        Frappeprice1:"5000 IQD",
        Frappeimg1:"",
         Frappename2:"کارامێل فراپێ",
        Frappeprice2:"5000 IQD",
        Frappeimg2:"",
         Frappename3:"کوکیز فراپێ",
        Frappeprice3:"5000 IQD",
        Frappeimg3:"",
         Frappename4:"فەرەولا فراپێ",
        Frappeprice4:"5000 IQD",
        Frappeimg4:"ئایس تی",
           Frappename5:"فەرەولا فراپێ",
        Frappeprice5:"5000 IQD",
        Frappeimg5:"",
         /* //////////////////////////////////////////////////*/
         Smoothie:"سموزی",
        Smoothiename1:"مانگو سموزی",
        Smoothieprice1:"4500 IQD",
        Smoothieimg1:"",
         Smoothiename2:"سموزیا فەرەولایێ",
        Smoothieprice2:"4500 IQD",
        Smoothieimg2:"",
         Smoothiename3:"بلوبێری سموزی",
        Smoothieprice3:"4500 IQD",
        Smoothieimg3:"",
         Smoothiename4:"پینا کولادا سموزی",
        Smoothieprice4:"4500 IQD",
        Smoothieimg4:"ئایس تی",
           Smoothiename5:"سموزیا خۆخێ",
       Smoothieprice5:"4500 IQD",
        Smoothieimg5:"",
            Smoothiename6:"ئەلفا سموزی",
        Smoothieprice6:"5500 IQD",
        Smoothieimg6:"",
        /* //////////////////////////////////////////////////*/
          IcedLatte:"ئایس لاتێ",
        IcedLattename1:"ئایس لاتێ",
        IcedLatteprice1:"4500 IQD",
        IcedLatteimg1:"",
         IcedLattename2:"ئایس ڤانێلا لاتێ",
        IcedLatteprice2:"5000 IQD",
        IcedLatteimg2:"",
         IcedLattename3:"ئایس کارامێل لاتێ",
        IcedLatteprice3:"5000 IQD",
        IcedLatteimg3:"",
         IcedLattename4:"ئایس لاتێیا فستەقێ",
        IcedLatteprice4:"5000 IQD",
        IcedLatteimg4:"",
         IcedLattename5:"ئایس لوتوس لاتێ",
        IcedLatteprice5:"5000 IQD",
        IcedLatteimg5:"",
         IcedLattename6:"ئایس موکا",
        IcedLatteprice6:"5000 IQD",
        IcedLatteimg6:"",
         IcedLattename7:"ئایس وایت موکا",
        IcedLatteprice7:"5000 IQD",
        IcedLatteimg7:"",
         IcedLattename8:"ئایس روز لاتێ",
        IcedLatteprice8:"5000 IQD",
        IcedLatteimg8:"",
        IcedLattename9:"ئایس سپانش لاتێ",
        IcedLatteprice9:"5000 IQD",
        IcedLatteimg9:"",
        IcedLattename10:"ئایس کوکونات لاتێ",
        IcedLatteprice10:"5000 IQD",
        IcedLatteimg10:"",
         IcedLattename11:"ئایس ستروبێری لاتێ",
        IcedLatteprice11:"5000 IQD",
        IcedLatteimg11:"",
         IcedLattename12:"ئایس لاڤندر لاتێ",
        IcedLatteprice12:"5000 IQD",
        IcedLatteimg12:"",
          /* //////////////////////////////////////////////////*/
          HotLatte:"لاتێیێن گەرم",
        HotLattename1:"کافێ لاتێ",
        HotLatteprice1:"4000 IQD",
        HotLatteimg1:"",
         HotLattename2:"ڤانێلا لاتێ",
        HotLatteprice2:"4500 IQD",
        HotLatteimg2:"",
         HotLattename3:"کارامێل لاتێ",
        HotLatteprice3:"4500 IQD",
        HotLatteimg3:"",
         HotLattename4:"سپانش لاتێ",
        HotLatteprice4:"4500 IQD",
        HotLatteimg4:"",
         HotLattename5:"لوتوس لاتێ",
        HotLatteprice5:"4500 IQD",
        HotLatteimg5:"",
         HotLattename6:"لاتێیا فستەقێ",
        HotLatteprice6:"4500 IQD",
        HotLatteimg6:"",
         HotLattename7:"روز لاتێ",
        HotLatteprice7:"4500 IQD",
        HotLatteimg7:"",
         HotLattename8:"موکا لاتێ",
        HotLatteprice8:"4500 IQD",
        HotLatteimg8:"",
        HotLattename9:"وایت موکا لاتێ",
        HotLatteprice9:"4500 IQD",
        HotLatteimg9:"",
        HotLattename10:"کوکونات لاتێ",
        HotLatteprice10:"4500 IQD",
        HotLatteimg10:"",
         HotLattename11:"لاڤندر لاتێ",
        HotLatteprice11:"4500 IQD",
        HotLatteimg11:"",
/* //////////////////////////////////////////////////*/
         HotDrinks:"ڤەخوارنێن گەرم",
        HotDrinksname1:"ئێسپرێسو",
        HotDrinksprice1:"2500 IQD",
        HotDrinksimg1:"",

HotDrinksname2:"دەبل ئێسپرێسو",
        HotDrinksprice2:"3500 IQD",
        HotDrinksimg2:"",
         HotDrinksname3:"ریسترێتو",
        HotDrinksprice3:"2500 IQD",
        HotDrinksimg3:"",
         HotDrinksname4:"ماکیاتو",
        HotDrinksprice4:"3000 IQD",
        HotDrinksimg4:"",
         HotDrinksname5:"لونگو",
        HotDrinksprice5:"3000 IQD",
        HotDrinksimg5:"",
         HotDrinksname6:"کون پانا",
        HotDrinksprice6:"3500 IQD",
        HotDrinksimg6:"",
         HotDrinksname7:"ئەمریکانو",
        HotDrinksprice7:"4000 IQD",
        HotDrinksimg7:"",
         HotDrinksname8:"کورتادو",
        HotDrinksprice8:"4000 IQD",
        HotDrinksimg8:"",
        HotDrinksname9:"ئەفوکادو",
        HotDrinksprice9:"3500 IQD",
        HotDrinksimg9:"",
        HotDrinksname10:"فلات وایت",
        HotDrinksprice10:"4000 IQD",
        HotDrinksimg10:"",
         HotDrinksname11:"پیکولو لاتێ",
        HotDrinksprice11:"4000 IQD",
        HotDrinksimg11:"",
         HotDrinksname12:"کێمێکس",
        HotDrinksprice12:"5000 IQD",
        HotDrinksimg12:"",
         HotDrinksname13:"ڤی60",
        HotDrinksprice13:"5000 IQD",
        HotDrinksimg13:"",
         HotDrinksname14:"قەهوا تورکی",
        HotDrinksprice14:"2000 IQD",
        HotDrinksimg14:"",
         HotDrinksname15:"دەبل شوت قەهوا تورکی",
        HotDrinksprice15:"3000 IQD",
        HotDrinksimg15:"",
         HotDrinksname16:"قەهوا عەرەبی",
        HotDrinksprice16:"2000 IQD",
        HotDrinksimg16:"",
         HotDrinksname17:"دەبل شوت قەهوا عەرەبی",
        HotDrinksprice17:"3000 IQD",
        HotDrinksimg17:"",
         HotDrinksname18:"قەهوا مستەکی",
        HotDrinksprice18:"2000 IQD",
        HotDrinksimg18:"",
         HotDrinksname19:"دەبل شوت قەهوا مستەکی",
        HotDrinksprice19:"3000 IQD",
        HotDrinksimg19:"",
         HotDrinksname20:"قەهوا کەزانا",
        HotDrinksprice20:"2000 IQD",
        HotDrinksimg20:"",
        HotDrinksname21:"دەبل شوت قەهوا کەزانا",
        HotDrinksprice21:"3000 IQD",
        HotDrinksimg21:"",
        HotDrinksname22:"هوت چوکلێت",
        HotDrinksprice22:"4000 IQD",
        HotDrinksimg22:"",
         HotDrinksname23:"سەحلەب",
        HotDrinksprice23:"4000 IQD",
        HotDrinksimg23:"",
         HotDrinksname24:"شیر",
        HotDrinksprice24:"2500 IQD",
        HotDrinksimg24:"",
           HotDrinksname25:"شیرێ ب هنگڤین",
        HotDrinksprice25:"3500 IQD",
        HotDrinksimg25:"",
           HotDrinksname26:"نیسکافی",
        HotDrinksprice26:"4000 IQD",
        HotDrinksimg26:"",
           HotDrinksname27:"کەپەچینو",
        HotDrinksprice27:"4000 IQD",
        HotDrinksimg27:"",
         /* //////////////////////////////////////////////////*/
         EnergyMix:" ڤەخوارنێن وزەبەخش",
        EnergyMixname1:"میکس رێدبول ئەلفا",
        EnergyMixprice1:"5500 IQD",
        EnergyMiximg1:"",
         EnergyMixname2:"رێدبول میکس",
       EnergyMixprice2:"4500 IQD",
        EnergyMiximg2:"",
         EnergyMixname3:"سمارت میکس ئەلفا",
        EnergyMixprice3:"3500 IQD",
        EnergyMiximg3:"",
         EnergyMixname4:"سمارت میکس",
        EnergyMixprice4:"2500 IQD",
        EnergyMiximg4:"ئایس تی",
           EnergyMixname5:"وایت تایگر میکس ئەلفا",
       EnergyMixprice5:"4000 IQD",
        EnergyMiximg5:"",
            EnergyMixname6:"وایت تایگر میکس",
        EnergyMixprice6:"3500 IQD",
       EnergyMiximg6:"",
        /* //////////////////////////////////////////////////*/
         Desserts:"شریناهی",
        Dessertsname1: "چیز کێک بلوبێری", Dessertsprice1: "4000 IQD", Dessertsimg1: "",
        Dessertsname2: "چیز کێک لۆتس", Dessertsprice2: "4000 IQD", Dessertsimg2: "",
        Dessertsname3: "چیز کێک بستاشیو", Dessertsprice3: "4000 IQD", Dessertsimg3: "",
        Dessertsname4: "چیز کێک ئۆریۆ", Dessertsprice4: "4000 IQD", Dessertsimg4: "",
        Dessertsname5: "ترالێچێ کەرەمێل", Dessertsprice5: "2000 IQD", Dessertsimg5: "",
        Dessertsname6: "تیرامیسو", Dessertsprice6: "3000 IQD", Dessertsimg6: "",
        Dessertsname7: "کێکێ ڕێد فێلفێت سلايس", Dessertsprice7: "3000 IQD", Dessertsimg7: "",
        Dessertsname8: "کێکێ بستاشیو سلايس", Dessertsprice8: "3000 IQD", Dessertsimg8: "",
        Dessertsname9: "کێکێ بلوبێری سلايس", Dessertsprice9: "3000 IQD", Dessertsimg9: "",
        Dessertsname10: "کێکێ بلاک فۆرێست سلايس", Dessertsprice10: "4000 IQD", Dessertsimg10: "",
        Dessertsname11: "کێکێ ماتیڵدا سلايس", Dessertsprice11: "4000 IQD", Dessertsimg11: "",
        Dessertsname12:"کریپ",
        Dessertsprice12:"4000 IQD",
        Dessertsimg12:"",
         Dessertsname13:"مینی پانکێک",
       Dessertsprice13:"4000 IQD",
       Dessertsimg13: "",
       /* /////////////////// Pastries Badini /////////////////// */
        Pastries: "فەتايێر",
        Pastriesname1: "فەتايێرا پەتاتێ",
        Pastriesprice1: "750 IQD",
        Pastriesimg1: "",
        Pastriesname2: "فەتايێرا پەنیری و قەشتێ",
        Pastriesprice2: "750 IQD",
        Pastriesimg2: "",
        Pastriesname3: "لۆرک",
        Pastriesprice3: "750 IQD",
        Pastriesimg3: "",
        Pastriesname4: "فەتايێرا نوتێلا",
        Pastriesprice4: "750 IQD",
        Pastriesimg4: "",
        Pastriesname5: "سۆجەک",
        Pastriesprice5: "500 IQD",
        Pastriesimg5: "",
        Pastriesname6: "سمیت",
        Pastriesprice6: "500 IQD",
        Pastriesimg6: "",
        Pastriesname7: "سمیتێ بچیک یێ تژی کری",
        Pastriesprice7: "500 IQD",
        Pastriesimg7: "",
        Pastriesname8: "ميني گژنيز",
        Pastriesprice8: "500 IQD",
        Pastriesimg8: "",
        Pastriesname9: "مینی پیتزا",
        Pastriesprice9: "1500 IQD",
        Pastriesimg9: "",
        Pastriesname10: " مینی پەنێر",
        Pastriesprice10: "1500 IQD",
        Pastriesimg10: "",
        Pastriesname11: "  مینی لۆرک ",
        Pastriesprice11: "1500 IQD",
        Pastriesimg11: "",
  /* ///////////////////  Pastriesperkilo /////////////////// */
                  Pastriesperkilo:"معجنات بالكيلو",
        Pastriesperkiloname1:"برازق",
        Pastriesperkiloprice1:"8000 IQD",
        Pastriesperkiloimg1:"",
         Pastriesperkiloname2:"برازق دايت",
        Pastriesperkiloprice2:"10000 IQD",
        Pastriesperkiloimg2:"",
         Pastriesperkiloname3:"شكرلمك تركي",
        Pastriesperkiloprice3:"8000 IQD",
        Pastriesperkiloimg3:"",
         Pastriesperkiloname4:"ماكارون كوكونات",
        Pastriesperkiloprice4:"12000 IQD",
        Pastriesperkiloimg4:"",
           Pastriesperkiloname5:"شابورا",
        Pastriesperkiloprice5:"12000 IQD",
        Pastriesperkiloimg5:"",
        /* /////////////////// Croissant Badini /////////////////// */
        Croissant: "کرواسان",
        Croissantname1: "کرواسانا سادە", Croissantprice1: "1500 IQD", Croissantimg1: "",
        Croissantname2: "کرواسانا پالمێری", Croissantprice2: "2000 IQD", Croissantimg2: "",
        Croissantname3: "کرواسانا ب زەعتر", Croissantprice3: "2000 IQD", Croissantimg3: "",
        Croissantname4: "کرواسانا ب شوکولاتێ", Croissantprice4: "2000 IQD", Croissantimg4: "",
        Croissantname5: "کرواسانا نۆتێلا", Croissantprice5: "3000 IQD", Croissantimg5: "",
        Croissantname6: "کرواسانا تژی کری ب فواکه", Croissantprice6: "3000 IQD", Croissantimg6: "",
        Croissantname7: "کرواسانا ب پستاشیو", Croissantprice7: "4000 IQD", Croissantimg7: "",
        Croissantname8: "کرواسانا شوکولاتا دوبەی", Croissantprice8: "5000 IQD", Croissantimg8: "",
        Croissantname9: "کرواسانا تارت بلوبێری", Croissantprice9: "4000 IQD", Croissantimg9: "",
        Croissantname10: "کرواسانا تارت فرێز", Croissantprice10: "4000 IQD", Croissantimg10: "",
        Croissantname11: "نیویورک رول کرواسان", Croissantprice11: "4000 IQD", Croissantimg11: "",
        Croissantname12: "سکوێر کرواسانا تژی کری", Croissantprice12: "4000 IQD", Croissantimg12: "",
        /* /////////////////// Donuts Badini /////////////////// */
        Donuts: "دۆنات",
        Donutsname1: "دۆناتا دێکور کری", Donutsprice1: "1500 IQD", Donutsimg1: "",
        Donutsname2: "دۆناتا تژی کری ب نۆتێلا", Donutsprice2: "3000 IQD", Donutsimg2: "",
        Donutsname3: "دۆناتا تژی کری ب بلوبێری", Donutsprice3: "3000 IQD", Donutsimg3: "",
        Donutsname4: "دۆناتا تژی کری ب فرێزێ", Donutsprice4: "3000 IQD", Donutsimg4: "",
        Donutsname5: "دۆناتا تژی کری ب کریم پاستری", Donutsprice5: "2000 IQD", Donutsimg5: "",
        Donutsname6: "دۆناتا تژی کری ب شوکولاتا دوبەی", Donutsprice6: "3000 IQD", Donutsimg6: "",
        Donutsname7: "مینی دۆناتا ب شەکرێ", Donutsprice7: "250 IQD", Donutsimg7: "",
        Donutsname8: "مینی دۆناتا دێکور کری", Donutsprice8: "750 IQD", Donutsimg8: "",
        Donutsname9: "مینی دۆناتا تژی کری", Donutsprice9: "1000 IQD", Donutsimg9: "",
        /* /////////////////// Eclair Badini /////////////////// */
        Eclair: "ئەکلێر",
        Eclairname1: "ئەکلێرێ پستاشيو", Eclairprice1: "2000 IQD", Eclairimg1: "",
        Eclairname2: "ئەکلێرێ لۆتس", Eclairprice2: "2000 IQD", Eclairimg2: "",
        Eclairname3: "ئەکلێرێ ئۆریۆ", Eclairprice3: "2000 IQD", Eclairimg3: "",
        Eclairname4: "ئەکلێرێ بلوبێری", Eclairprice4: "2000 IQD", Eclairimg4: "",
        /* /////////////////// Cookies Badini /////////////////// */
        Cookies: "كوكيز",
        Cookiesname1: "کۆکیز ب نۆتێلا", Cookiesprice1: "2500 IQD", Cookiesimg1: "",
        Cookiesname2: "کۆکیز ب کیندەر", Cookiesprice2: "2500 IQD", Cookiesimg2: "",
        Cookiesname3: "کۆکیز ب مانگۆ", Cookiesprice3: "2500 IQD", Cookiesimg3: "",
        Cookiesname4: "کۆکیز ڕێد فێلفێت", Cookiesprice4: "2500 IQD", Cookiesimg4: "",
        Cookiesname5: "کۆکیز سادە", Cookiesprice5: "2000 IQD", Cookiesimg5: "",
        Cookiesname6: "کۆکیز ب پستاشيو", Cookiesprice6: "2500 IQD", Cookiesimg6: "",
         /* ///////////////////  zmnan /////////////////// */
  /* ///////////////////  zman /////////////////// */
w1:"خوارنا روژئاڤايى",
w2:"خوارنا روژهەلاتى",
alpharest:"خوارنگەها ئەلفا",
/* /////////////////// Pizza Badini /////////////////// */
        Pizza: "پیتزا",
        Pizzaname1: "پیتزا تێکەڵ (میکس)", Pizzaprice1: "11,000 IQD", Pizzaimg1: "",
        Pizzaname2: "پیتزا سەوزەوات", Pizzaprice2: "8,000 IQD", Pizzaimg2: "",
        Pizzaname3: "پیتزا ڤالیو", Pizzaprice3: "9,000 IQD", Pizzaimg3: "",
        Pizzaname4: "پیتزا گۆشت", Pizzaprice4: "11,000 IQD", Pizzaimg4: "",
        Pizzaname5: "پیتزا مریشک", Pizzaprice5: "9,000 IQD", Pizzaimg5: "",
        Pizzaname6: "پیتزا پێپەرۆنی", Pizzaprice6: "9,000 IQD", Pizzaimg6: "",
        Pizzaname7: "پیتزا چپس", Pizzaprice7: "11,000 IQD", Pizzaimg7: "",
        Pizzaname8: "پیتزا توونا", Pizzaprice8: "9,000 IQD", Pizzaimg8: "",
        Pizzaname9: "پیتزا مریشک و چپس", Pizzaprice9: "9,000 IQD", Pizzaimg9: "",
        Pizzaname10: "پیتزا مەکسیکی", Pizzaprice10: "11,000 IQD", Pizzaimg10: "",
        Pizzaname11: "پیتزا کالزۆنی", Pizzaprice11: "10,000 IQD", Pizzaimg11: "",
        Pizzaname12: "پیتزا مارگاریتا", Pizzaprice12: "7,000 IQD", Pizzaimg12: "",
        Pizzaname13: "پیتزا زارۆکان", Pizzaprice13: "7,000 IQD", Pizzaimg13: "",
        Pizzaname14: "پیتزا چاوچاو", Pizzaprice14: "9,000 IQD", Pizzaimg14: "",
        /* /////////////////// Burger Badini /////////////////// */
        Burger: "بەرگەر",
        Burgername1: "بەرگەرا گۆشتی", Burgerprice1: "5,000 IQD", Burgerimg1: "",
        Burgername2: "بەرگەرا مریشکێ", Burgerprice2: "4,000 IQD", Burgerimg2: "",
        Burgername3: "چیزبەرگەرا مریشکێ", Burgerprice3: "7,000 IQD", Burgerimg3: "",
        Burgername4: "چیزبەرگەرا گۆشتی", Burgerprice4: "8,000 IQD", Burgerimg4: "",
        Burgername5: "دەبڵ بەرگەرا گۆشتی", Burgerprice5: "12,000 IQD", Burgerimg5: "",
        Burgername6: "دەبڵ بەرگەرا مریشکێ", Burgerprice6: "11,000 IQD", Burgerimg6: "",
        Burgername7: "ئەلفا بەرگەر (گۆشت)", Burgerprice7: "12,000 IQD", Burgerimg7: "",
        Burgername8: "ئەلفا بەرگەرا مریشکێ", Burgerprice8: "10,000 IQD", Burgerimg8: "",
        /* /////////////////// Sandwich Badini /////////////////// */
        Sandwich: "ساندویچ",
        Sandwichname1: "ساندویچا مریشکێ", Sandwichprice1: "7,000 IQD", Sandwichimg1: "",
        Sandwichname2: "ساندویچا گۆشتی", Sandwichprice2: "10,000 IQD", Sandwichimg2: "",
        Sandwichname3: "ساندویچا چپس", Sandwichprice3: "9,000 IQD", Sandwichimg3: "",
        /* /////////////////// Chicken & Saj Badini /////////////////// */
        ChickenSaj: "مریشک و ساج",
        ChickenSajname1: "مریشکا رۆڵ", ChickenSajprice1: "4,000 IQD", ChickenSajimg1: "",
        ChickenSajname2: "مریشکا پیتا", ChickenSajprice2: "3,000 IQD", ChickenSajimg2: "",
        ChickenSajname3: "ساجا مریشکێ", ChickenSajprice3: "7,000 IQD", ChickenSajimg3: "",
        ChickenSajname4: "ئالفا ساجا مریشکێ", ChickenSajprice4: "10,000 IQD", ChickenSajimg4: "",
        ChickenSajname5: "ساجا مریشک و چپس", ChickenSajprice5: "8,000 IQD", ChickenSajimg5: "",
        ChickenSajname6: "ئیسکالۆبا مریشکێ", ChickenSajprice6: "8,000 IQD", ChickenSajimg6: "",
        ChickenSajname7: "کەنتاکیا زارۆکان", ChickenSajprice7: "6,000 IQD", ChickenSajimg7: "",
        /* /////////////////// Meat & Saj Badini /////////////////// */
        MeatSaj: "گۆشت و ساج",
        MeatSajname1: "گۆشتێ رۆڵ", MeatSajprice1: "6,000 IQD", MeatSajimg1: "",
        MeatSajname2: "ئالفا رۆڵ", MeatSajprice2: "8,000 IQD", MeatSajimg2: "",
        MeatSajname3: "گۆشتێ پیتا", MeatSajprice3: "4,000 IQD", MeatSajimg3: "",
        MeatSajname4: "ئالفا پیتا", MeatSajprice4: "5,000 IQD", MeatSajimg4: "",
        MeatSajname5: "ساجێ گۆشتی", MeatSajprice5: "9,000 IQD", MeatSajimg5: "",
        MeatSajname6: "ساجێ گۆشت و چپس", MeatSajprice6: "10,000 IQD", MeatSajimg6: "",
        MeatSajname7: "ئالفا ساجێ گۆشتی", MeatSajprice7: "11,000 IQD", MeatSajimg7: "",
        /* /////////////////// Fries Badini /////////////////// */
        Fries: "فینگەر",
        Appetizersname1: "فینگەر سوورکری", Appetizersprice1: "3,000 IQD", Appetizersimg1: "",
        Appetizersname2: "فینگەر چیتۆس", Appetizersprice2: "6,000 IQD", Appetizersimg2: "",
        Appetizersname3: "فینگەر ب پەنیر", Appetizersprice3: "5,000 IQD", Appetizersimg3: "",
        Appetizersname4: "فینگەر وێدجس", Appetizersprice4: "5,000 IQD", Appetizersimg4: "",
        Appetizersname5: "گەنمۆک (زەرت)", Appetizersprice5: "5,000 IQD", Appetizersimg5: "",
        Appetizersname6: "کەلەکێن پیڤازێ", Appetizersprice6: "5,000 IQD", Appetizersimg6: "",
        Appetizersname7: "فینگەر برژاندى", Appetizersprice7: "6,000 IQD", Appetizersimg7: "",
        /* /////////////////// Alpha Special Badini /////////////////// */
        AlphaSpecial: "ئەلفا سبيشيل",
        AlphaSpecialname1: "ئەلفا مریشک", AlphaSpecialprice1: "9,000 IQD", AlphaSpecialimg1: "",
        AlphaSpecialname2: "ئەلفا کەباب", AlphaSpecialprice2: "12,000 IQD", AlphaSpecialimg2: "",
        AlphaSpecialname3: "بێلیزا مریشک", AlphaSpecialprice3: "13,000 IQD", AlphaSpecialimg3: "",
        AlphaSpecialname4: "ساندویچێ گۆشتێ چێلێ", AlphaSpecialprice4: "12,000 IQD", AlphaSpecialimg4: "",
        AlphaSpecialname5: "ئالفا گریک", AlphaSpecialprice5: "12,000 IQD", AlphaSpecialimg5: "",
        AlphaSpecialname6: "ئەلفا بێلیزا مریشک", AlphaSpecialprice6: "13,000 IQD", AlphaSpecialimg6: "",
        AlphaSpecialname7: "ئەلفا پۆلۆ مریشک", AlphaSpecialprice7: "11,000 IQD", AlphaSpecialimg7: "",
        AlphaSpecialname8: "ئەلفا پۆلۆ", AlphaSpecialprice8: "13,000 IQD", AlphaSpecialimg8: "",
        AlphaSpecialname9: "بێلیزا گەنمۆک", AlphaSpecialprice9: "13,000 IQD", AlphaSpecialimg9: "",
        AlphaSpecialname10: "بێلیزا مریشک و گەنمۆک", AlphaSpecialprice10: "12,000 IQD", AlphaSpecialimg10: "",
        AlphaSpecialname11: "گۆشت و قارچک", AlphaSpecialprice11: "13,000 IQD", AlphaSpecialimg11: "",
        AlphaSpecialname12: "ئەلفا بێلیزا", AlphaSpecialprice12: "14,000 IQD", AlphaSpecialimg12: "",
        /* /////////////////// Box Meals Badini /////////////////// */
        BoxMeals: "بوكسا خوارنێ",
        BoxMealsname1: "بوكسا مریشکێ", BoxMealsprice1: "8,000 IQD", BoxMealsimg1: "",
        BoxMealsname2: "بوكسا گۆشتی", BoxMealsprice2: "10,000 IQD", BoxMealsimg2: "",
        BoxMealsname3: "ئەلفا بوكسا گۆشتی", BoxMealsprice3: "11,000 IQD", BoxMealsimg3: "",
        BoxMealsname4: "ئەلفا بوكسا مریشکێ", BoxMealsprice4: "10,000 IQD", BoxMealsimg4: "",
        BoxMealsname5: "بوكسا شەوارمێ", BoxMealsprice5: "4,000 IQD", BoxMealsimg5: "",
        BoxMealsname6: "بوكسا شەوارما مریشکێ", BoxMealsprice6: "6,000 IQD", BoxMealsimg6: "",
        /* /////////////////// Pasta Badini /////////////////// */
        Pasta: "پاستا",
        Pastaname1: "پاستایا مریشکێ", Pastaprice1: "9,000 IQD", Pastaimg1: "",
        Pastaname2: "پاستایا گۆشتی", Pastaprice2: "10,000 IQD", Pastaimg2: "",
        Pastaname3: "فیتوچینی ئەلفرێدۆ", Pastaprice3: "10,000 IQD", Pastaimg3: "",
        Pastaname4: "فیتوچینی مریشکێ", Pastaprice4: "9,000 IQD", Pastaimg4: "",
        Pastaname5: "فیتوچینی", Pastaprice5: "10,000 IQD", Pastaimg5: "",
        /* /////////////////// Diet Meals Badini /////////////////// */
        DietMeals: "خوارنێن دایت",
        DietMealsname1: "مریشکا دایت", DietMealsprice1: "7,000 IQD", DietMealsimg1: "",
        DietMealsname2: "گۆشتێ دایت", DietMealsprice2: "11,000 IQD", DietMealsimg2: "",
        DietMealsname3: "سەلەمۆنێ دایت", DietMealsprice3: "14,000 IQD", DietMealsimg3: "",
        /* /////////////////// Steak Badini /////////////////// */
        Steak: "ستێیک",
        Steakname1: "ستێیکا گۆشتی", Steakprice1: "14,000 IQD", Steakimg1: "",
        Steakname2: "ستێیکا مریشکێ", Steakprice2: "12,000 IQD", Steakimg2: "",
        Steakname3: "ئەلفا ستی بێلیزا", Steakprice3: "12,000 IQD", Steakimg3: "",
        Steakname4: "ستێیکا سەلەمۆنی", Steakprice4: "16,000 IQD", Steakimg4: "",
          /* /////////////////// Shrimp Arabic /////////////////// */
        Shrimp: "روبيان",
        Shrimpname1: "روبيان", Shrimpprice1: "15,000 IQD", Shrimpimg1: "",
        Shrimpname2: "روبيان تیژ ", Shrimpprice2: "12,000 IQD", Shrimpimg2: "",
        /* /////////////////// Salads Badini /////////////////// */
        Salads: "زەڵاتە",
        Saladsname1: "زەڵاتەیا سیزەر", Saladsprice1: "6,000 IQD", Saladsimg1: "",
        Saladsname2: "زەڵاتەیا فرۆکا", Saladsprice2: "5,000 IQD", Saladsimg2: "",
        Saladsname3: "زەڵاتەیا برۆکۆلی", Saladsprice3: "7,000 IQD", Saladsimg3: "",
        Saladsname4: "زەڵاتەیا یۆنانی", Saladsprice4: "5,000 IQD", Saladsimg4: "",
        Saladsname5: "زەڵاتەیا ڕۆکا (کێوەر)", Saladsprice5: "5,000 IQD", Saladsimg5: "",
        cola: "ڤەخوارن",
        colaname1: "کۆلا", colaprice1: "500 IQD", colaimg1: "",
        colaname2: "سپرایت", colaprice2: "500 IQD", colaimg2: "",
        colaname3: "فانتا", colaprice3: "500 IQD", colaimg3: "",
        colaname4: "ئاڤ", colaprice4: "250 IQD", colaimg4: "",
        dir: "rtl"

    },























    ar: {
        welcome_text: "أهلاً بكم",
        nav:"مطعم",
        nav1:"bakery",
        alphabakery:"ألفا بێکری",
        mojito:"موهيتو",
        path:"../../assets/test.jpeg",

        /* /////////////////// Mojito Arabic /////////////////// */
        mojitoname1: "كلاسيك مۆهيتو",
        mojitoprice1: "3500 IQD",
        mojitoimg1: "",
        mojitoname2: "فراولة مۆهيتو",
        mojitoprice2: "4000 IQD",
        mojitoimg2: "",
        mojitoname3: "بلو هاواي مۆهيتو",
        mojitoprice3: "4000 IQD",
        mojitoimg3: "",
        mojitoname4: "رمان مۆهيتو",
        mojitoprice4: "4000 IQD",
        mojitoimg4: "",
        mojitoname5: "خوخ مۆهيتو",
        mojitoprice5: "4000 IQD",
        mojitoimg5: "",
        mojitoname6: "باشن فروت مۆهيتو",
        mojitoprice6: "4000 IQD",
        mojitoimg6: "",
        mojitoname7: "توت أزرق مۆهيتو",
        mojitoprice7: "4000 IQD",
        mojitoimg7: "",
        mojitoname8: "مانجو مۆهيتو",
        mojitoprice8: "4000 IQD",
        mojitoimg8: "",
        mojitoname9: "أناناس مۆهيتو",
        mojitoprice9: "4000 IQD",
        mojitoimg9: "",
        mojitoname10: "ألفا مۆهيتو",
        mojitoprice10: "5000 IQD",
        mojitoimg10: "",

        /* /////////////////// Juice Arabic /////////////////// */
        Juice: "عصائر",
        Juicename1: "برتقال",
        Juiceprice1: "4000 IQD",
        Juiceimg1: "",
        Juicename2: "رمان",
        Juiceprice2: "4000 IQD",
        Juiceimg2: "",
        Juicename3: "ليمون نعناع",
        Juiceprice3: "4000 IQD",
        Juiceimg3: "",
        Juicename4: "أناناس",
        Juiceprice4: "4000 IQD",
        Juiceimg4: "",
        Juicename5: "مانجو",
        Juiceprice5: "5000 IQD",
        Juiceimg5: "",
        Juicename6: "موز بالحليب",
        Juiceprice6: "4000 IQD",
        Juiceimg6: "",
        Juicename7: "أفوكادو",
        Juiceprice7: "5000 IQD",
        Juiceimg7: "",
        Juicename8: "كوكتيل",
        Juiceprice8: "4000 IQD",
        Juiceimg8: "",
        Juicename9: "ألفا",
        Juiceprice9: "5500 IQD",
        Juiceimg9: "",
       
        /* /////////////////// Ice Tea Arabic /////////////////// */
        IceTea: "آيس تي",
        IceTeaname1: "آيس تي خوخ",
        IceTeaprice1: "5000 IQD",
        IceTeaimg1: "",
        IceTeaname2: "آيس تي ليمون",
        IceTeaprice2: "5000 IQD",
        IceTeaimg2: "",
        IceTeaname3: "آيس تي مانجو",
        IceTeaprice3: "5000 IQD",
        IceTeaimg3: "",
        IceTeaname4: "آيس تي باشن فروت",
        IceTeaprice4: "5000 IQD",
        IceTeaimg4: "", // لێرەدا دەقەکە لادراوە بۆ ئەوەی وێنە دابنێیت
        /* /////////////////// Mocktail Arabic /////////////////// */
        Mocktail: "موكتيل",
        Mocktailname1: "ألفا موكتيل",
        Mocktailprice1: "6000 IQD",
        Mocktailimg1: "",
        Mocktailname2: "لافندر موكتيل",
        Mocktailprice2: "5000 IQD",
        Mocktailimg2: "",
        Mocktailname3: "بينا كولادا موكتيل",
        Mocktailprice3: "5000 IQD",
        Mocktailimg3: "",
        Mocktailname4: "بيري بلاست موكتيل",
        Mocktailprice4: "5000 IQD",
        Mocktailimg4: "",
        Mocktailname5: "أوشن دريم موكتيل",
        Mocktailprice5: "5000 IQD",
        Mocktailimg5: "",
        /* /////////////////// Milkshake Arabic /////////////////// */
        Milkshake: "ميلك شيك",
        Milkshakename1: "نوتيلا ميلك شيك",
        Milkshakeprice1: "5000 IQD",
        Milkshakeimg1: "",
        Milkshakename2: "لوتس ميلك شيك",
        Milkshakeprice2: "5000 IQD",
        Milkshakeimg2: "",
        Milkshakename3: "فستق ميلك شيك",
        Milkshakeprice3: "5000 IQD",
        Milkshakeimg3: "",
        Milkshakename4: "فانيليا ميلك شيك",
        Milkshakeprice4: "5000 IQD",
        Milkshakeimg4: "",
        Milkshakename5: "أوريو ميلك شيك",
        Milkshakeprice5: "5000 IQD",
        Milkshakeimg5: "",
        Milkshakename6: "كيندر ميلك شيك",
        Milkshakeprice6: "5000 IQD",
        Milkshakeimg6: "",
        Milkshakename7: "فراولة ميلك شيك",
        Milkshakeprice7: "5000 IQD",
        Milkshakeimg7: "",
        Milkshakename8: "شوكولاتة ميلك شيك",
        Milkshakeprice8: "5000 IQD",
        Milkshakeimg8: "",
        Milkshakename9: "كراميل ميلك شيك",
        Milkshakeprice9: "5000 IQD",
        Milkshakeimg9: "",
        Milkshakename10: "ألفا ميلك شيك",
        Milkshakeprice10: "6000 IQD",
        Milkshakeimg10: "",
        /* /////////////////// Frappe Arabic /////////////////// */
        Frappe: "فرابيه",
        Frappename1: "فرابيه شوكولاتة",
        Frappeprice1: "5000 IQD",
        Frappeimg1: "",
        Frappename2: "فرابيه كراميل",
        Frappeprice2: "5000 IQD",
        Frappeimg2: "",
        Frappename3: "فرابيه كوكيز",
        Frappeprice3: "5000 IQD",
        Frappeimg3: "", // هەمان کلیل کە لە لیستی ئینگلیزییەکە هەبوو
        Frappename4: "فرابيه فراولة",
        Frappeprice4: "5000 IQD",
        Frappeimg4: "",
        Frappename5: "فرابيه فراولة",
        Frappeprice5: "5000 IQD",
        Frappeimg5: "",
        /* /////////////////// Smoothie Arabic /////////////////// */
        Smoothie: "سموذي",
        Smoothiename1: "سموذي مانجو",
        Smoothieprice1: "4500 IQD",
        Smoothieimg1: "",
        Smoothiename2: "سموذي فراولة",
        Smoothieprice2: "4500 IQD",
        Smoothieimg2: "",
        Smoothiename3: "سموذي توت أزرق",
        Smoothieprice3: "4500 IQD",
        Smoothieimg3: "",
        Smoothiename4: "سموذي بينا كولادا",
        Smoothieprice4: "4500 IQD",
        Smoothieimg4: "",
        Smoothiename5: "سموذي خوخ",
        Smoothieprice5: "4500 IQD",
        Smoothieimg5: "",
        Smoothiename6: "ألفا سموذي",
        Smoothieprice6: "5500 IQD",
        Smoothieimg6: "",
        /* /////////////////// Iced Latte Arabic /////////////////// */
        IcedLatte: "آيس لاتيه",
        IcedLattename1: "آيس لاتيه",
        IcedLatteprice1: "4500 IQD",
        IcedLatteimg1: "",
        IcedLattename2: "آيس ڤانيلا لاتيه",
        IcedLatteprice2: "5000 IQD",
        IcedLatteimg2: "",
        IcedLattename3: "آيس كراميل لاتيه",
        IcedLatteprice3: "5000 IQD",
        IcedLatteimg3: "",
        IcedLattename4: "آيس فستق لاتيه",
        IcedLatteprice4: "5000 IQD",
        IcedLatteimg4: "",
        IcedLattename5: "آيس لوتس لاتيه",
        IcedLatteprice5: "5000 IQD",
        IcedLatteimg5: "",
        IcedLattename6: "آيس موكا",
        IcedLatteprice6: "5000 IQD",
        IcedLatteimg6: "",
        IcedLattename7: "آيس وايت موكا",
        IcedLatteprice7: "5000 IQD",
        IcedLatteimg7: "",
        IcedLattename8: "آيس روز لاتيه",
        IcedLatteprice8: "5000 IQD",
        IcedLatteimg8: "",
        IcedLattename9: "آيس سبانش لاتيه",
        IcedLatteprice9: "5000 IQD",
        IcedLatteimg9: "",
        IcedLattename10: "آيس جوز الهند لاتيه",
        IcedLatteprice10: "5000 IQD",
        IcedLatteimg10: "",
        IcedLattename11: "آيس فراولة لاتيه",
        IcedLatteprice11: "5000 IQD",
        IcedLatteimg11: "",
        IcedLattename12: "آيس لافندر لاتيه",
        IcedLatteprice12: "5000 IQD",
        IcedLatteimg12: "",
        HotLatte: "هوت لاتيه",
        HotLattename1: "كافيه لاتيه",
        HotLatteprice1: "4000 IQD",
        HotLatteimg1: "",
        HotLattename2: "ڤانيلا لاتيه",
        HotLatteprice2: "4500 IQD",
        HotLatteimg2: "",
        HotLattename3: "كراميل لاتيه",
        HotLatteprice3: "4500 IQD",
        HotLatteimg3: "",
        HotLattename4: "سبانش لاتيه",
        HotLatteprice4: "4500 IQD",
        HotLatteimg4: "",
        HotLattename5: "لوتس لاتيه",
        HotLatteprice5: "4500 IQD",
        HotLatteimg5: "",
        HotLattename6: "فستق لاتيه",
        HotLatteprice6: "4500 IQD",
        HotLatteimg6: "",
        HotLattename7: "روز لاتيه",
        HotLatteprice7: "4500 IQD",
        HotLatteimg7: "",
        HotLattename8: "موكا لاتيه",
        HotLatteprice8: "4500 IQD",
        HotLatteimg8: "",
        HotLattename9: "وايت موكا لاتيه",
        HotLatteprice9: "4500 IQD",
        HotLatteimg9: "",
        HotLattename10: "جوز الهند لاتيه",
        HotLatteprice10: "4500 IQD",
        HotLatteimg10: "",
        HotLattename11: "لافندر لاتيه",
        HotLatteprice11: "4500 IQD",
        HotLatteimg11: "",
        /* /////////////////// Hot Drinks Arabic /////////////////// */
        HotDrinks: "مشروبات ساخنة",
        HotDrinksname1: "إسبريسو سينجل",
        HotDrinksprice1: "2500 IQD",
        HotDrinksimg1: "",
        HotDrinksname2: "إسبريسو دبل",
        HotDrinksprice2: "3500 IQD",
        HotDrinksimg2: "",
        HotDrinksname3: "ريستريتو",
        HotDrinksprice3: "2500 IQD",
        HotDrinksimg3: "",
        HotDrinksname4: "ماكياتو",
        HotDrinksprice4: "3000 IQD",
        HotDrinksimg4: "",
        HotDrinksname5: "لونغو",
        HotDrinksprice5: "3000 IQD",
        HotDrinksimg5: "",
        HotDrinksname6: "كون بانا",
        HotDrinksprice6: "3500 IQD",
        HotDrinksimg6: "",
        HotDrinksname7: "أمريكانو",
        HotDrinksprice7: "4000 IQD",
        HotDrinksimg7: "",
        HotDrinksname8: "كورتادو",
        HotDrinksprice8: "4000 IQD",
        HotDrinksimg8: "",
        HotDrinksname9: "أفوغاتو",
        HotDrinksprice9: "3500 IQD",
        HotDrinksimg9: "",
        HotDrinksname10: "فلات وايت",
        HotDrinksprice10: "4000 IQD",
        HotDrinksimg10: "",
        HotDrinksname11: "بيكولو لاتيه",
        HotDrinksprice11: "4000 IQD",
        HotDrinksimg11: "",
        HotDrinksname12: "كيمكس",
        HotDrinksprice12: "5000 IQD",
        HotDrinksimg12: "",
        HotDrinksname13: "V60",
        HotDrinksprice13: "5000 IQD",
        HotDrinksimg13: "",
        HotDrinksname14: "قهوة تركية",
        HotDrinksprice14: "2000 IQD",
        HotDrinksimg14: "",
        HotDrinksname15: "قهوة تركية دبل",
        HotDrinksprice15: "3000 IQD",
        HotDrinksimg15: "",
        HotDrinksname16: "قهوة عربية",
        HotDrinksprice16: "2000 IQD",
        HotDrinksimg16: "",
        HotDrinksname17: "قهوة عربية دبل",
        HotDrinksprice17: "3000 IQD",
        HotDrinksimg17: "",
        HotDrinksname18: "قهوة مستكة",
        HotDrinksprice18: "2000 IQD",
        HotDrinksimg18: "",
        HotDrinksname19: "قهوة مستكة دبل",
        HotDrinksprice19: "3000 IQD",
        HotDrinksimg19: "",
        HotDrinksname20: "قهوة كازان",
        HotDrinksprice20: "2000 IQD",
        HotDrinksimg20: "",
        HotDrinksname21: "قهوة كازان دبل",
        HotDrinksprice21: "3000 IQD",
        HotDrinksimg21: "",
        HotDrinksname22: "هوت شوكليت",
        HotDrinksprice22: "4000 IQD",
        HotDrinksimg22: "",
        HotDrinksname23: "سحلب",
        HotDrinksprice23: "4000 IQD",
        HotDrinksimg23: "",
        HotDrinksname24: "حليب سادة",
        HotDrinksprice24: "2500 IQD",
        HotDrinksimg24: "",
        HotDrinksname25: "حليب بالعسل",
        HotDrinksprice25: "3500 IQD",
        HotDrinksimg25: "",
        HotDrinksname26: "نسكافيه",
        HotDrinksprice26: "4000 IQD",
        HotDrinksimg26: "",
        HotDrinksname27: "كابيتشينو",
        HotDrinksprice27: "4000 IQD",
        HotDrinksimg27: "",
        /* /////////////////// Energy Mix Arabic /////////////////// */
        EnergyMix: "ميكس الطاقة",
        EnergyMixname1: "ريد بول ميكس ألفا",
        EnergyMixprice1: "5500 IQD",
        EnergyMiximg1: "",
        EnergyMixname2: "ريد بول ميكس",
        EnergyMixprice2: "4500 IQD",
        EnergyMiximg2: "",
        EnergyMixname3: "سمارت ميكس ألفا",
        EnergyMixprice3: "3500 IQD",
        EnergyMiximg3: "",
        EnergyMixname4: "سمارت ميكس",
        EnergyMixprice4: "2500 IQD",
        EnergyMiximg4: "",
        EnergyMixname5: "وايت تايجر ميكس ألفا",
        EnergyMixprice5: "4000 IQD",
        EnergyMiximg5: "",
        EnergyMixname6: "وايت تايجر ميكس",
        EnergyMixprice6: "3500 IQD",
        EnergyMiximg6: "",
        /* /////////////////// Desserts Arabic /////////////////// */
       /* /////////////////// Desserts Arabic /////////////////// */
        Desserts: "حلويات",
        Dessertsname1: "تشيز كيك بلو بيري", Dessertsprice1: "4000 IQD", Dessertsimg1: "",
        Dessertsname2: "تشيز كيك لوتس", Dessertsprice2: "4000 IQD", Dessertsimg2: "",
        Dessertsname3: "تشيز كيك بستاشيو", Dessertsprice3: "4000 IQD", Dessertsimg3: "",
        Dessertsname4: "تشيز كيك أوريو", Dessertsprice4: "4000 IQD", Dessertsimg4: "",
        Dessertsname5: "تريليتشا كراميل", Dessertsprice5: "2000 IQD", Dessertsimg5: "",
        Dessertsname6: "تيراميسو", Dessertsprice6: "3000 IQD", Dessertsimg6: "",
        Dessertsname7: "كيك ريد فيلفيت سلايس", Dessertsprice7: "3000 IQD", Dessertsimg7: "",
        Dessertsname8: "كيك بستاشيو سلايس", Dessertsprice8: "3000 IQD", Dessertsimg8: "",
        Dessertsname9: "كيك بلو بيري سلايس", Dessertsprice9: "3000 IQD", Dessertsimg9: "",
        Dessertsname10: "كيك بلاك فورست سلايس", Dessertsprice10: "4000 IQD", Dessertsimg10: "",
        Dessertsname11: "كيك ماتيلدا سلايس", Dessertsprice11: "4000 IQD", Dessertsimg11: "",
        Dessertsname12: "كريب",
        Dessertsprice12: "4000 IQD",
        Dessertsimg12: "",
        Dessertsname13: "ميني بان كيك",
        Dessertsprice13: "4000 IQD",
        Dessertsimg13: "",
        /* /////////////////// Pastries Arabic /////////////////// */
        Pastries: "فطيرة",
        Pastriesname1: "فطيرة بطاطس",
        Pastriesprice1: "750 IQD",
        Pastriesimg1: "",
        Pastriesname2: "فطيرة جبنة وقشطة",
        Pastriesprice2: "750 IQD",
        Pastriesimg2: "",
        Pastriesname3: "لورك",
        Pastriesprice3: "750 IQD",
        Pastriesimg3: "",
        Pastriesname4: "فطيرة نوتيلا",
        Pastriesprice4: "750 IQD",
        Pastriesimg4: "",
        Pastriesname5: "سجق",
        Pastriesprice5: "500 IQD",
        Pastriesimg5: "",
        Pastriesname6: "سميت",
        Pastriesprice6: "500 IQD",
        Pastriesimg6: "",
        Pastriesname7: "ميني سميت محشي",
        Pastriesprice7: "500 IQD",
        Pastriesimg7: "",
        Pastriesname8: "فطيرة كزبرة ميني",
        Pastriesprice8: "500 IQD",
        Pastriesimg8: "",
        Pastriesname9: "ميني بيتزا",
        Pastriesprice9: "1500 IQD",
        Pastriesimg9: "",
        Pastriesname10: "فطيرة جبنة ميني",
        Pastriesprice10: "1500 IQD",
        Pastriesimg10: "",
        Pastriesname11: "فطيرة جبنة لورك ميني",
        Pastriesprice11: "1500 IQD",
        Pastriesimg11: "",
        /* ///////////////////  Pastriesperkilo /////////////////// */
                  Pastriesperkilo:"معجنات بالكيلو",
        Pastriesperkiloname1:"برازق",
        Pastriesperkiloprice1:"8000 IQD",
        Pastriesperkiloimg1:"",
         Pastriesperkiloname2:"برازق دايت",
        Pastriesperkiloprice2:"10000 IQD",
        Pastriesperkiloimg2:"",
         Pastriesperkiloname3:"شكرلمك تركي",
        Pastriesperkiloprice3:"8000 IQD",
        Pastriesperkiloimg3:"",
         Pastriesperkiloname4:"ماكارون كوكونات",
        Pastriesperkiloprice4:"12000 IQD",
        Pastriesperkiloimg4:"",
           Pastriesperkiloname5:"شابورا",
        Pastriesperkiloprice5:"12000 IQD",
        Pastriesperkiloimg5:"",
        /* /////////////////// Croissant Arabic /////////////////// */
        Croissant: "كرواسان",
        Croissantname1: "كرواسان سادة", Croissantprice1: "1500 IQD", Croissantimg1: "",
        Croissantname2: "كرواسان بالمير", Croissantprice2: "2000 IQD", Croissantimg2: "",
        Croissantname3: "كرواسان بالزعتر", Croissantprice3: "2000 IQD", Croissantimg3: "",
        Croissantname4: "كرواسان شوكولاتة", Croissantprice4: "2000 IQD", Croissantimg4: "",
        Croissantname5: "كرواسان نوتيلا", Croissantprice5: "3000 IQD", Croissantimg5: "",
        Croissantname6: "كرواسان محشي فواكه", Croissantprice6: "3000 IQD", Croissantimg6: "",
        Croissantname7: "كرواسان بيستاشيو", Croissantprice7: "4000 IQD", Croissantimg7: "",
        Croissantname8: "كرواسان شوكولاتة دبي", Croissantprice8: "5000 IQD", Croissantimg8: "",
        Croissantname9: "كرواسان تارت بلوبيري", Croissantprice9: "4000 IQD", Croissantimg9: "",
        Croissantname10: "كرواسان تارت فراولة", Croissantprice10: "4000 IQD", Croissantimg10: "",
        Croissantname11: "كرواسان نيويورك رول", Croissantprice11: "4000 IQD", Croissantimg11: "",
        Croissantname12: "كرواسان سكوير محشي", Croissantprice12: "4000 IQD", Croissantimg12: "",
        /* /////////////////// Donuts Arabic /////////////////// */
        Donuts: "دونات",
        Donutsname1: "دونات ديكور", Donutsprice1: "1500 IQD", Donutsimg1: "",
        Donutsname2: "دونات محشي نوتيلا", Donutsprice2: "3000 IQD", Donutsimg2: "",
        Donutsname3: "دونات محشي بلوبيري", Donutsprice3: "3000 IQD", Donutsimg3: "",
        Donutsname4: "دونات محشي فراولة", Donutsprice4: "3000 IQD", Donutsimg4: "",
        Donutsname5: "دونات محشي كريم باستري", Donutsprice5: "2000 IQD", Donutsimg5: "",
        Donutsname6: "دونات محشي شوكولاتة دبي", Donutsprice6: "3000 IQD", Donutsimg6: "",
        Donutsname7: "ميني دونات سكر", Donutsprice7: "250 IQD", Donutsimg7: "",
        Donutsname8: "ميني دونات ديكور", Donutsprice8: "750 IQD", Donutsimg8: "",
        Donutsname9: "ميني دونات محشي", Donutsprice9: "1000 IQD", Donutsimg9: "",
        /* /////////////////// Eclair Badini /////////////////// */
        Eclair: "ئەکلێر",
        Eclairname1: "ئەکلێرێ پستاشيو", Eclairprice1: "2000 IQD", Eclairimg1: "",
        Eclairname2: "ئەکلێرێ لۆتس", Eclairprice2: "2000 IQD", Eclairimg2: "",
        Eclairname3: "ئەکلێرێ ئۆریۆ", Eclairprice3: "2000 IQD", Eclairimg3: "",
        Eclairname4: "ئەکلێرێ بلوبێری", Eclairprice4: "2000 IQD", Eclairimg4: "",
        /* /////////////////// Cookies Arabic /////////////////// */
        Cookies: "كوكيز",
        Cookiesname1: "نوتيلا كوكيز", Cookiesprice1: "2500 IQD", Cookiesimg1: "",
        Cookiesname2: "كيندر كوكيز", Cookiesprice2: "2500 IQD", Cookiesimg2: "",
        Cookiesname3: "مانجو كوكيز", Cookiesprice3: "2500 IQD", Cookiesimg3: "",
        Cookiesname4: "ريد فيلفيت كوكيز", Cookiesprice4: "2500 IQD", Cookiesimg4: "",
        Cookiesname5: "كوكيز سادة", Cookiesprice5: "2000 IQD", Cookiesimg5: "",
        Cookiesname6: "بيستاشيو كوكيز", Cookiesprice6: "2500 IQD", Cookiesimg6: "",
              /* ///////////////////  zmnan /////////////////// */
  /* ///////////////////  zman /////////////////// */
w1:"الأكل الغربي",
w2:"الأكل الشرقي",
alpharest:"مطعم ألفا",
/* /////////////////// Pizza Arabic /////////////////// */
        Pizza: "بيتزا",
        Pizzaname1: "بيتزا مشكل", Pizzaprice1: "11,000 IQD", Pizzaimg1: "",
        Pizzaname2: "بيتزا خضروات", Pizzaprice2: "8,000 IQD", Pizzaimg2: "",
        Pizzaname3: "بيتزا ڤاليو", Pizzaprice3: "9,000 IQD", Pizzaimg3: "",
        Pizzaname4: "بيتزا لحم", Pizzaprice4: "11,000 IQD", Pizzaimg4: "",
        Pizzaname5: "بيتزا دجاج", Pizzaprice5: "9,000 IQD", Pizzaimg5: "",
        Pizzaname6: "بيتزا ببروني", Pizzaprice6: "9,000 IQD", Pizzaimg6: "",
        Pizzaname7: "بيتزا شيبس", Pizzaprice7: "11,000 IQD", Pizzaimg7: "",
        Pizzaname8: "بيتزا تونة", Pizzaprice8: "9,000 IQD", Pizzaimg8: "",
        Pizzaname9: "بيتزا دجاج وشيبس", Pizzaprice9: "9,000 IQD", Pizzaimg9: "",
        Pizzaname10: "بيتزا مكسيكية", Pizzaprice10: "11,000 IQD", Pizzaimg10: "",
        Pizzaname11: "بيتزا كالتزوني", Pizzaprice11: "10,000 IQD", Pizzaimg11: "",
        Pizzaname12: "بيتزا مارغريتا", Pizzaprice12: "7,000 IQD", Pizzaimg12: "",
        Pizzaname13: "بيتزا أطفال", Pizzaprice13: "7,000 IQD", Pizzaimg13: "",
        Pizzaname14: "بيتزا چاو چاو", Pizzaprice14: "9,000 IQD", Pizzaimg14: "",
        /* /////////////////// Burger Arabic /////////////////// */
        Burger: "برجر",
        Burgername1: "برجر لحم", Burgerprice1: "5,000 IQD", Burgerimg1: "",
        Burgername2: "برجر دجاج", Burgerprice2: "4,000 IQD", Burgerimg2: "",
        Burgername3: "تشيز برجر دجاج", Burgerprice3: "7,000 IQD", Burgerimg3: "",
        Burgername4: "تشيز برجر لحم", Burgerprice4: "8,000 IQD", Burgerimg4: "",
        Burgername5: "دبل برجر لحم", Burgerprice5: "12,000 IQD", Burgerimg5: "",
        Burgername6: "دبل برجر دجاج", Burgerprice6: "11,000 IQD", Burgerimg6: "",
        Burgername7: "ألفا برجر (لحم)", Burgerprice7: "12,000 IQD", Burgerimg7: "",
        Burgername8: "ألفا برجر دجاج", Burgerprice8: "10,000 IQD", Burgerimg8: "",
        /* /////////////////// Sandwich Arabic /////////////////// */
        Sandwich: "ساندويتش",
        Sandwichname1: "ساندويتش دجاج", Sandwichprice1: "7,000 IQD", Sandwichimg1: "",
        Sandwichname2: "ساندويتش لحم", Sandwichprice2: "10,000 IQD", Sandwichimg2: "",
        Sandwichname3: "ساندويتش شيبس", Sandwichprice3: "9,000 IQD", Sandwichimg3: "",
        /* /////////////////// Chicken & Saj Arabic /////////////////// */
        ChickenSaj: "دجاج وصاج",
        ChickenSajname1: "رول دجاج", ChickenSajprice1: "4,000 IQD", ChickenSajimg1: "",
        ChickenSajname2: "دجاج بيتا", ChickenSajprice2: "3,000 IQD", ChickenSajimg2: "",
        ChickenSajname3: "صاج دجاج", ChickenSajprice3: "7,000 IQD", ChickenSajimg3: "",
        ChickenSajname4: "ألفا صاج دجاج", ChickenSajprice4: "10,000 IQD", ChickenSajimg4: "",
        ChickenSajname5: "صاج دجاج وشيبس", ChickenSajprice5: "8,000 IQD", ChickenSajimg5: "",
        ChickenSajname6: "اسكالوب دجاج", ChickenSajprice6: "8,000 IQD", ChickenSajimg6: "",
        ChickenSajname7: "كنتاكي أطفال", ChickenSajprice7: "6,000 IQD", ChickenSajimg7: "",
        /* /////////////////// Meat & Saj Arabic /////////////////// */
        MeatSaj: "لحم وصاج",
        MeatSajname1: "رول لحم", MeatSajprice1: "6,000 IQD", MeatSajimg1: "",
        MeatSajname2: "ألفا رول", MeatSajprice2: "8,000 IQD", MeatSajimg2: "",
        MeatSajname3: "لحم بيتا", MeatSajprice3: "4,000 IQD", MeatSajimg3: "",
        MeatSajname4: "ألفا بيتا", MeatSajprice4: "5,000 IQD", MeatSajimg4: "",
        MeatSajname5: "صاج لحم", MeatSajprice5: "9,000 IQD", MeatSajimg5: "",
        MeatSajname6: "صاج لحم وشيبس", MeatSajprice6: "10,000 IQD", MeatSajimg6: "",
        MeatSajname7: "ألفا صاج لحم", MeatSajprice7: "11,000 IQD", MeatSajimg7: "",
        /* /////////////////// Fries Arabic /////////////////// */
        Fries: "فینکر",
        Appetizersname1: "فینکر مقلية", Appetizersprice1: "3,000 IQD", Appetizersimg1: "",
        Appetizersname2: "فینکر تشيتوس", Appetizersprice2: "6,000 IQD", Appetizersimg2: "",
        Appetizersname3: "فینکر بالجبنة", Appetizersprice3: "5,000 IQD", Appetizersimg3: "",
        Appetizersname4: "فینکر ودجز", Appetizersprice4: "5,000 IQD", Appetizersimg4: "",
        Appetizersname5: "ذرة", Appetizersprice5: "5,000 IQD", Appetizersimg5: "",
        Appetizersname6: "حلقات البصل", Appetizersprice6: "5,000 IQD", Appetizersimg6: "",
        Appetizersname7: "فینکر مشوية", Appetizersprice7: "6,000 IQD", Appetizersimg7: "",
        /* /////////////////// Alpha Special Arabic /////////////////// */
        AlphaSpecial: "ألفا سبيشيل",
        AlphaSpecialname1: "ألفا دجاج", AlphaSpecialprice1: "9,000 IQD", AlphaSpecialimg1: "",
        AlphaSpecialname2: "ألفا كباب", AlphaSpecialprice2: "12,000 IQD", AlphaSpecialimg2: "",
        AlphaSpecialname3: "بليزا دجاج", AlphaSpecialprice3: "13,000 IQD", AlphaSpecialimg3: "",
        AlphaSpecialname4: "ساندويتش لحم بقري", AlphaSpecialprice4: "12,000 IQD", AlphaSpecialimg4: "",
        AlphaSpecialname5: "ألفا جريك", AlphaSpecialprice5: "12,000 IQD", AlphaSpecialimg5: "",
        AlphaSpecialname6: "ألفا بليزا دجاج", AlphaSpecialprice6: "13,000 IQD", AlphaSpecialimg6: "",
        AlphaSpecialname7: "ألفا بولو دجاج", AlphaSpecialprice7: "11,000 IQD", AlphaSpecialimg7: "",
        AlphaSpecialname8: "ألفا بولو", AlphaSpecialprice8: "13,000 IQD", AlphaSpecialimg8: "",
        AlphaSpecialname9: "بليزا ذرة", AlphaSpecialprice9: "13,000 IQD", AlphaSpecialimg9: "",
        AlphaSpecialname10: "بليزا دجاج وذرة", AlphaSpecialprice10: "12,000 IQD", AlphaSpecialimg10: "",
        AlphaSpecialname11: "لحم بالفطر", AlphaSpecialprice11: "13,000 IQD", AlphaSpecialimg11: "",
        AlphaSpecialname12: "ألفا بليزا", AlphaSpecialprice12: "14,000 IQD", AlphaSpecialimg12: "",
        /* /////////////////// Box Meals Arabic /////////////////// */
        BoxMeals: "بوكسات",
        BoxMealsname1: "بوكس دجاج", BoxMealsprice1: "8,000 IQD", BoxMealsimg1: "",
        BoxMealsname2: "بوكس لحم", BoxMealsprice2: "10,000 IQD", BoxMealsimg2: "",
        BoxMealsname3: "ألفا بوكس لحم", BoxMealsprice3: "11,000 IQD", BoxMealsimg3: "",
        BoxMealsname4: "ألفا بوكس دجاج", BoxMealsprice4: "10,000 IQD", BoxMealsimg4: "",
        BoxMealsname5: "بوكس شاورما", BoxMealsprice5: "4,000 IQD", BoxMealsimg5: "",
        BoxMealsname6: "بوكس شاورما دجاج", BoxMealsprice6: "6,000 IQD", BoxMealsimg6: "",
        /* /////////////////// Pasta Arabic /////////////////// */
        Pasta: "باستا",
        Pastaname1: "باستا دجاج", Pastaprice1: "9,000 IQD", Pastaimg1: "",
        Pastaname2: "باستا لحم", Pastaprice2: "10,000 IQD", Pastaimg2: "",
        Pastaname3: "فيتوتشيني ألفريدو", Pastaprice3: "10,000 IQD", Pastaimg3: "",
        Pastaname4: "فيتوتشيني دجاج", Pastaprice4: "9,000 IQD", Pastaimg4: "",
        Pastaname5: "فيتوتشيني", Pastaprice5: "10,000 IQD", Pastaimg5: "",
        /* /////////////////// Diet Meals Arabic /////////////////// */
        DietMeals: "وجبات دايت",
        DietMealsname1: "دجاج دايت", DietMealsprice1: "7,000 IQD", DietMealsimg1: "",
        DietMealsname2: "لحم دايت", DietMealsprice2: "11,000 IQD", DietMealsimg2: "",
        DietMealsname3: "سلمون دايت", DietMealsprice3: "14,000 IQD", DietMealsimg3: "",
        /* /////////////////// Steak Arabic /////////////////// */
        Steak: "ستيك",
        Steakname1: "ستيك لحم", Steakprice1: "14,000 IQD", Steakimg1: "",
        Steakname2: "ستيك دجاج", Steakprice2: "12,000 IQD", Steakimg2: "",
        Steakname3: "ألفا ستيبيليزا", Steakprice3: "12,000 IQD", Steakimg3: "",
        Steakname4: "ستيك سلمون", Steakprice4: "16,000 IQD", Steakimg4: "",
        /* /////////////////// Shrimp Arabic /////////////////// */
        Shrimp: "روبيان",
        Shrimpname1: "روبيان", Shrimpprice1: "15,000 IQD", Shrimpimg1: "",
        Shrimpname2: "روبيان حار ", Shrimpprice2: "12,000 IQD", Shrimpimg2: "",
        /* /////////////////// Salads Arabic /////////////////// */
        Salads: "سلطات",
        Saladsname1: "سلطة سيزر", Saladsprice1: "6,000 IQD", Saladsimg1: "",
        Saladsname2: "سلطة فروكا", Saladsprice2: "5,000 IQD", Saladsimg2: "",
        Saladsname3: "سلطة بروكلي", Saladsprice3: "7,000 IQD", Saladsimg3: "",
        Saladsname4: "سلطة يونانية", Saladsprice4: "5,000 IQD", Saladsimg4: "",
        Saladsname5: "سلطة جرجير (روكا)", Saladsprice5: "5,000 IQD", Saladsimg5: "",
        cola: "المشروبات",
        colaname1: "كولا", colaprice1: "500 IQD", colaimg1: "",
        colaname2: "سبرايت", colaprice2: "500 IQD", colaimg2: "",
        colaname3: "فانتا", colaprice3: "500 IQD", colaimg3: "",
        colaname4: "ماء", colaprice4: "250 IQD", colaimg4: "",
        dir: "rtl"
    }
      
    }
        
   

// فەنکشن بۆ دیاریکردنی زمان
function setLang(lang) {
    localStorage.setItem('selectedLang', lang);
    applyLanguage();
}

// جێبەجێکردنی وەرگێڕان لەسەر پەرەکان
function applyLanguage() {
    // ئەگەر پێشتر زمان دیاری نەکرابوو، با ئینگلیزی بێت بە بنەڕەت
    const currentLang = localStorage.getItem('selectedLang') || 'en';
    const data = translations[currentLang];

    // گۆڕینی ئاراستەی لاپەڕە (RTL/LTR)
    document.documentElement.dir = data.dir;
    document.documentElement.lang = currentLang;

    // گۆڕینی هەموو ئەو دەقانەی data-key یان هەیە
    document.querySelectorAll('[data-key]').forEach(element => {
        const key = element.getAttribute('data-key');
        if (data[key]) {
            element.innerText = data[key];
        }
    });

    // ڕەنگکردنی دوگمەی زمانی هەڵبژێردراو
    document.querySelectorAll('.lang-btn').forEach(btn => {
        btn.classList.remove('active');
        // پشکنین بەپێی دەقەکە یان پارامیتەرەکە
        if (btn.getAttribute('onclick').includes(`'${currentLang}'`)) {
            btn.classList.add('active');
        }
    });
}
function applyLanguage() {
    const currentLang = localStorage.getItem('selectedLang') || 'en';
    const data = translations[currentLang];

    // گۆڕینی ئاراستەی لاپەڕە
    document.documentElement.dir = data.dir;
    document.documentElement.lang = currentLang;

    // گۆڕینی هەموو ئەو توخمانەی data-key یان هەیە
    document.querySelectorAll('[data-key]').forEach(element => {
        const key = element.getAttribute('data-key');
        if (data[key]) {
            // پشکنین: ئەگەر توخمەکە وێنە بوو src بگۆڕە، ئەگەر نا innerText
            if (element.tagName === "IMG") {
                element.src = data[key];
            } else {
                element.innerText = data[key];
            }
        }
    });
}
// کاتی بارکردنی لاپەڕە، بانگی وەرگێڕان بکە
document.addEventListener('DOMContentLoaded', applyLanguage);